# Generated by Django 5.2.11 on 2026-08-26 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('professionals', '0002_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_code', models.CharField(help_text='Stable template code; unique within tenant and client with version.', max_length=60)),
                ('template_name', models.CharField(help_text='Template display name.', max_length=180)),
                ('version', models.CharField(help_text='Template version; versioned publication process.', max_length=30)),
                ('output_type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('HTML', 'HTML')], help_text='Generated file format.', max_length=20)),
                ('template_storage_key', models.CharField(blank=True, help_text='Uploaded source template file (tenant-prefixed object-storage key).', max_length=600)),
                ('mapping_schema', models.JSONField(blank=True, default=dict, help_text='Field-to-template mapping configuration: sections, source tokens, transforms, repeat and display rules.')),
                ('required_fields_schema', models.JSONField(blank=True, default=dict, help_text='Template completeness requirements: mandatory mappings and gap questions.')),
                ('confidentiality_rules', models.JSONField(blank=True, default=dict, help_text='Masking and sensitive-data rules; cannot permit restricted fields without explicit approved rule and consent.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', help_text='Publication status.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Availability status; only active published templates can create final outputs.')),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication timestamp; required when PUBLISHED.', null=True)),
                ('retired_at', models.DateTimeField(blank=True, help_text='Retirement timestamp; required when retired.', null=True)),
                ('client_organization', models.ForeignKey(blank=True, help_text='Client that owns/requests the format. Same tenant; CLIENT type recommended.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resume_templates', to='tenancy.organization')),
                ('created_by', models.ForeignKey(help_text='Template creator; same-tenant Tenant Admin or authorised template manager.', on_delete=django.db.models.deletion.PROTECT, related_name='resume_templates_created', to='accounts.usertbl')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'ResumeTemplate',
                'verbose_name_plural': 'ResumeTemplates',
                'db_table': 'resumes_resume_template',
                'ordering': ['template_code', 'version'],
            },
        ),
        migrations.CreateModel(
            name='ResumeGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Safe external identifier used in APIs and integrations.', unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('SUBMITTED', 'Submitted'), ('SUPERSEDED', 'Superseded'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='Generation workflow status.', max_length=30)),
                ('source_snapshot', models.JSONField(help_text='Source data used for the output; immutable after generation; sensitive values masked/encrypted as required.')),
                ('override_values', models.JSONField(blank=True, default=dict, help_text='Output-only approved overrides; only template fields marked user-overridable; never changes core profile.')),
                ('consent_snapshot', models.JSONField(blank=True, default=dict, help_text='Consent state used for generation: applicable consent/declaration versions and timestamps.')),
                ('validation_result', models.JSONField(blank=True, default=dict, help_text='Template readiness validation: missing, unverified, confidential and restricted-field results.')),
                ('output_storage_key', models.CharField(blank=True, help_text='Generated resume file location (tenant-prefixed object-storage key).', max_length=600)),
                ('output_hash', models.CharField(blank=True, help_text='Generated file integrity hash (SHA-256 or stronger).', max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Required for approved review state.', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Required when status=SUBMITTED.', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Generation timestamp.')),
                ('generated_by', models.ForeignKey(help_text='User who triggered generation; same tenant, must have permission.', on_delete=django.db.models.deletion.PROTECT, related_name='resume_generations_created', to='accounts.usertbl')),
                ('professional', models.ForeignKey(help_text='Professional whose resume is generated.', on_delete=django.db.models.deletion.PROTECT, related_name='resume_generations', to='professionals.professionalprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Reviewer; same-tenant authorised reviewer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resume_generations_reviewed', to='accounts.usertbl')),
                ('supersedes', models.ForeignKey(blank=True, help_text='Prior resume generation replaced by this one. Same professional/tenant; cannot form cycle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='resumes.resumegeneration')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('resume_template', models.ForeignKey(help_text='Template version used; same tenant, published for final output.', on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='resumes.resumetemplate')),
            ],
            options={
                'verbose_name': 'ResumeGeneration',
                'verbose_name_plural': 'ResumeGeneration',
                'db_table': 'resumes_resume_generation',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='resumetemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'client_organization', 'template_code', 'version'), name='uniq_resume_template_tenant_client_code_version'),
        ),
        migrations.AddConstraint(
            model_name='resumetemplate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PUBLISHED'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='chk_resume_template_published_at_required'),
        ),
        migrations.AddConstraint(
            model_name='resumetemplate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'RETIRED'), _negated=True), ('retired_at__isnull', False), _connector='OR'), name='chk_resume_template_retired_at_required'),
        ),
        migrations.AddConstraint(
            model_name='resumegeneration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), ('reviewed_at__isnull', False), _connector='OR'), name='chk_resume_generation_reviewed_at_required'),
        ),
        migrations.AddConstraint(
            model_name='resumegeneration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'SUBMITTED'), _negated=True), ('submitted_at__isnull', False), _connector='OR'), name='chk_resume_generation_submitted_at_required'),
        ),
    ]
