# Generated by Django 5.2.11 on 2026-08-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumegeneration',
            options={'ordering': ['-generated_at'], 'verbose_name': 'ResumeGeneration', 'verbose_name_plural': 'ResumeGeneration'},
        ),
        migrations.AlterModelOptions(
            name='resumetemplate',
            options={'ordering': ['template_code', 'version'], 'verbose_name': 'ResumeTemplate', 'verbose_name_plural': 'ResumeTemplates'},
        ),
    ]
