# Generated by Django 5.2.11 on 2026-07-31 07:39

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('consent_type', models.CharField(choices=[('TERMS', 'Terms'), ('PRIVACY', 'Privacy'), ('RESUME_PROCESSING', 'Resume processing'), ('MARKETING', 'Marketing'), ('CLIENT_RESUME_SHARING', 'Client resume sharing'), ('REFERENCE_SHARING', 'Reference sharing'), ('PROFILE_ACCURACY', 'Profile accuracy'), ('CONFLICT_OF_INTEREST', 'Conflict of interest')], help_text='Type of consent or declaration.', max_length=40)),
                ('document_version', models.CharField(help_text='Version of the accepted document or wording.', max_length=30)),
                ('jurisdiction', models.CharField(blank=True, help_text='Applicable legal jurisdiction.', max_length=20)),
                ('is_granted', models.BooleanField(help_text='Whether consent was granted.')),
                ('granted_at', models.DateTimeField(blank=True, help_text='Grant timestamp.', null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, help_text='Withdrawal timestamp.', null=True)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('ADMIN', 'Admin'), ('IMPORT', 'Import')], default='WEB', help_text='Channel through which consent was recorded.', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Network address recorded for audit.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Client application/browser information.', max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='May hold client/template context or conflict details; no secrets.')),
            ],
            options={
                'verbose_name': 'Consent Record',
                'verbose_name_plural': 'Consent Records',
                'db_table': 'accounts_consent_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Safe external identifier used in APIs and integrations.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_version', models.PositiveIntegerField(default=1, help_text='Submission version; incremented for resubmission.')),
                ('selected_operating_country', models.CharField(help_text='Country of the tenant operation selected by user. Must match an active TenantOperation for selected industry.', max_length=2, validators=[django.core.validators.RegexValidator(code='invalid_country_code', message='Enter a valid ISO 3166-1 alpha-2 country code, e.g. AE.', regex='^[A-Z]{2}$')])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='Application workflow status.', max_length=30)),
                ('stage1_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of Stage 1 data reviewed by Tenant Admin. Immutable after submission; excludes password and OTP.')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Submission timestamp.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Review decision timestamp.', null=True)),
                ('decision_reason', models.TextField(blank=True, help_text='Review explanation.', max_length=2000)),
            ],
            options={
                'verbose_name': 'Registration Application',
                'verbose_name_plural': 'Registration Applications',
                'db_table': 'accounts_registration_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('TENANT_ADMIN', 'Tenant admin'), ('PROFESSIONAL', 'Professional'), ('REVIEWER', 'Reviewer')], max_length=16, unique=True)),
                ('name', models.CharField(help_text='Role name.', max_length=32)),
                ('roles_for', models.CharField(choices=[('super admin', 'super admin'), ('tenant admin', 'tenant admin')], default='super admin', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation.')),
            ],
        ),
        migrations.CreateModel(
            name='UserTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Safe external identifier used in APIs and integrations.', unique=True)),
                ('email', models.EmailField(help_text='Primary login and communication email.', max_length=254)),
                ('mobile_country_code', models.CharField(help_text='Country calling code stored separately.', max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_calling_code', message='Enter a valid international calling code, e.g. +1 or +971.', regex='^\\+[1-9]\\d{0,3}$')])),
                ('mobile_number', models.CharField(help_text='Mobile number for verification and recovery.', max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='Enter digits only, 10-15 digits.', regex='^\\d{10,15}$')])),
                ('password', models.CharField(help_text='Authentication secret. Minimum policy 12 characters; hashed by the authentication layer; never stored or returned as plain text.', max_length=128)),
                ('is_candidate', models.BooleanField(default=False, help_text='True only for candidates.')),
                ('is_mentor', models.BooleanField(default=False, help_text='True only for mentors.')),
                ('approval_status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING_APPROVAL', help_text='Tenant Admin approval state.', max_length=30)),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='Email verification timestamp.', null=True)),
                ('mobile_verified_at', models.DateTimeField(blank=True, help_text='Mobile verification timestamp.', null=True)),
                ('mfa_method', models.CharField(choices=[('NONE', 'None'), ('AUTHENTICATOR', 'Authenticator app'), ('SMS', 'SMS'), ('EMAIL', 'Email')], default='EMAIL', help_text='Selected two-factor authentication method.', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Approval timestamp.', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection or return.', max_length=2000)),
                ('is_active', models.BooleanField(default=False, help_text='Django authentication active flag. Set true only after approval and required verification; may be false for suspension.')),
                ('is_staff', models.BooleanField(default=False, help_text='Django Admin access flag.')),
                ('is_superuser', models.BooleanField(default=False, help_text='True only for Platform Super Admin; tenant must be NULL. Platform-wide superuser flag.')),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0, help_text='Failed authentication counter.')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Temporary lock expiry.', null=True)),
                ('last_login', models.DateTimeField(blank=True, help_text='Last successful login.', null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='User creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
                'ordering': ['email'],
            },
        ),
    ]
