# Generated by Django 5.2.11 on 2026-08-07 11:43

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('professionals', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='professional',
            field=models.ForeignKey(blank=True, help_text='Optional professional context. Required for profile/resume declarations when profile exists.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='tenant',
            field=models.ForeignKey(help_text='Same tenant as user and professional.', on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='NULL only for Platform Super Admin LOGIN/PASSWORD_RESET.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='registrationapplication',
            name='selected_industry',
            field=models.ForeignKey(help_text='Industry selected during Stage 1. Must be active INDUSTRY and assigned to tenant through TenantOperation.', on_delete=django.db.models.deletion.PROTECT, related_name='registration_applications', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='registrationapplication',
            name='selected_scope',
            field=models.ForeignKey(help_text='Primary inspection/survey scope. Scope.industry must equal selected_industry.', on_delete=django.db.models.deletion.PROTECT, related_name='registration_applications', to='catalog.scopecatalog'),
        ),
        migrations.AddField(
            model_name='registrationapplication',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant receiving the registration. Derived from the permanent tenant URL; cannot be changed by request payload.', on_delete=django.db.models.deletion.PROTECT, related_name='registration_applications', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='roles',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant registration and login context. Required for all non-platform users; NULL only for Platform Super Admin.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='usertbl',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Approver of the user account. Same-tenant Tenant Admin or Platform Super Admin; cannot approve self.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_approved', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='usertbl',
            name='role',
            field=models.ManyToManyField(blank=True, to='accounts.roles'),
        ),
        migrations.AddField(
            model_name='usertbl',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant registration and login context. Required for all non-platform users; NULL only for Platform Super Admin.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='registrationapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed the application. Must be same-tenant Tenant Admin or Platform Super Admin.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_applications_reviewed', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='registrationapplication',
            name='user',
            field=models.ForeignKey(help_text='Tenant-scoped user submitting the application. User.tenant must equal tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='registration_applications', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='user',
            field=models.ForeignKey(help_text='User giving or withdrawing consent. User.tenant must equal tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='accounts.usertbl'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['tenant', 'sent_to', 'otp_type', 'is_used'], name='idx_otp_tenant_sent_type'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['expires_at'], name='idx_otp_expires_at'),
        ),
        migrations.AddConstraint(
            model_name='otpverification',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='chk_otp_expires_after_created'),
        ),
        migrations.AddConstraint(
            model_name='usertbl',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('tenant'), name='uniq_user_tenant_lower_email'),
        ),
        migrations.AddConstraint(
            model_name='usertbl',
            constraint=models.UniqueConstraint(fields=('tenant', 'mobile_country_code', 'mobile_number'), name='uniq_user_tenant_mobile'),
        ),
        migrations.AddConstraint(
            model_name='usertbl',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approval_status', 'APPROVED'), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='chk_user_approved_at_required_when_approved'),
        ),
        migrations.AddConstraint(
            model_name='usertbl',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approval_status', 'REJECTED'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='chk_user_rejection_reason_required_when_rejected'),
        ),
        migrations.AddConstraint(
            model_name='registrationapplication',
            constraint=models.UniqueConstraint(fields=('tenant', 'user', 'application_version'), name='uniq_registration_application_tenant_user_version'),
        ),
        migrations.AddConstraint(
            model_name='registrationapplication',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('submitted_at__isnull', False), _connector='OR'), name='chk_registration_application_submitted_at_required'),
        ),
        migrations.AddConstraint(
            model_name='registrationapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['APPROVED', 'REJECTED', 'RETURNED']), _negated=True), ('reviewed_at__isnull', False), _connector='OR'), name='chk_registration_application_reviewed_at_required'),
        ),
        migrations.AddConstraint(
            model_name='registrationapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['REJECTED', 'RETURNED']), _negated=True), models.Q(('decision_reason', ''), _negated=True), _connector='OR'), name='chk_registration_application_decision_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('is_granted', False), ('granted_at__isnull', False), _connector='OR'), name='chk_consent_record_granted_at_required'),
        ),
        migrations.AddConstraint(
            model_name='consentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('withdrawn_at__isnull', True), ('granted_at__isnull', True), ('withdrawn_at__gt', models.F('granted_at')), _connector='OR'), name='chk_consent_record_withdrawn_after_granted'),
        ),
    ]
