# Generated by Django 5.2.11 on 2026-07-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
