# Generated by Django 5.2.11 on 2026-08-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapplication',
            name='decision_history',
            field=models.JSONField(blank=True, default=list, help_text='Append-only log of prior decision cycles (status, reason, reviewer, timestamp, version) — captured before each overwrite.'),
        ),
    ]
