# Generated by Django 5.2.11 on 2026-07-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_roles_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertbl',
            name='password',
            field=models.TextField(help_text='Authentication secret. Minimum policy 12 characters; hashed by the authentication layer; never stored or returned as plain text.'),
        ),
    ]
