# Generated by Django 5.2.11 on 2026-08-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registrationapplication_decision_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consentrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'ConsentRecord', 'verbose_name_plural': 'ConsentRecord'},
        ),
        migrations.AlterModelOptions(
            name='otpverification',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTPVerification', 'verbose_name_plural': 'OTPVerification'},
        ),
        migrations.AlterModelOptions(
            name='registrationapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'RegistrationApplication', 'verbose_name_plural': 'RegistrationApplication'},
        ),
        migrations.AlterModelOptions(
            name='usertbl',
            options={'ordering': ['email'], 'verbose_name': 'UserTbl', 'verbose_name_plural': 'UserTbl'},
        ),
    ]
