# Generated by Django 5.2.11 on 2026-07-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usertbl_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertbl',
            name='password',
            field=models.CharField(help_text='Authentication secret. Minimum policy 12 characters; hashed by the authentication layer; never stored or returned as plain text.', max_length=128),
        ),
    ]
