# Generated by Django 5.2.11 on 2026-08-01 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usertbl_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_type', models.CharField(choices=[('EMAIL', 'Email Verification'), ('MOBILE', 'Mobile Verification'), ('LOGIN', 'Login'), ('PASSWORD_RESET', 'Password Reset')], max_length=30)),
                ('otp', models.CharField(help_text='Hashed OTP; never stored or returned as plain text.', max_length=128)),
                ('sent_to', models.CharField(help_text='Actual destination address/number the OTP was sent to.', max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Failed verification attempt counter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='accounts.usertbl')),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'db_table': 'accounts_otp_verification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'otp_type', 'is_used'], name='idx_otp_user_type_used'), models.Index(fields=['expires_at'], name='idx_otp_expires_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='chk_otp_expires_after_created')],
            },
        ),
    ]
