# Generated by Django 5.2.11 on 2026-08-01 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otpverification'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otpverification',
            name='idx_otp_user_type_used',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='user',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='NULL only for Platform Super Admin LOGIN/PASSWORD_RESET.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='sent_to',
            field=models.CharField(help_text='Destination address/number; the matching key together with tenant and otp_type.', max_length=254),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['tenant', 'sent_to', 'otp_type', 'is_used'], name='idx_otp_tenant_sent_type'),
        ),
    ]
