# Generated by Django 5.2.11 on 2026-08-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_otpverification_idx_otp_user_type_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertbl',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Referral code of the user.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertbl',
            name='referral_source',
            field=models.CharField(blank=True, help_text='Referral source of the user.', max_length=100, null=True),
        ),
    ]
