# Generated by Django 5.2.11 on 2026-08-07 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assessment_type', models.CharField(choices=[('INITIAL', 'Initial'), ('PERIODIC', 'Periodic'), ('PROGRESSION', 'Progression'), ('AUTHORITY', 'Authority'), ('REVALIDATION', 'Revalidation')], help_text='Assessment purpose.', max_length=30)),
                ('assessor_role_snapshot', models.CharField(help_text='Assessor authority snapshot captured at assessment time.', max_length=60)),
                ('technical_knowledge_score', models.DecimalField(decimal_places=2, help_text='Technical knowledge dimension (0.00-100.00).', max_digits=5)),
                ('field_execution_score', models.DecimalField(decimal_places=2, help_text='Field execution discipline dimension (0.00-100.00).', max_digits=5)),
                ('documentation_evidence_score', models.DecimalField(decimal_places=2, help_text='Documentation and evidence quality dimension; threshold may block progression.', max_digits=5)),
                ('ethics_independence_score', models.DecimalField(decimal_places=2, help_text='Ethics and independence dimension; threshold may block progression.', max_digits=5)),
                ('communication_conduct_score', models.DecimalField(decimal_places=2, help_text='Communication and professional conduct dimension.', max_digits=5)),
                ('recommendation', models.TextField(help_text='Assessor recommendation and observations; evidence-based.', max_length=3000)),
                ('decision', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', help_text='Assessment decision state.', max_length=20)),
                ('decision_reason', models.TextField(blank=True, help_text='Required for rejection or override.', max_length=3000)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Required when decision=APPROVED/REJECTED.', null=True)),
                ('evidence_summary', models.JSONField(blank=True, default=dict, help_text='Evidence used in assessment; source record IDs and calculated metrics; immutable after decision.')),
                ('assessed_at', models.DateTimeField(help_text='Assessment date/time.')),
                ('approved_authority', models.ForeignKey(blank=True, help_text='Approved authority; required when decision=APPROVED.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competency_assessments_approved_authority', to='catalog.referencevalue')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Final approver; authorised approver; cannot be assessed professional; separation of duties where configured.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competency_assessments_approved', to='accounts.usertbl')),
                ('approved_level', models.ForeignKey(blank=True, help_text='Approved level; required when decision=APPROVED.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competency_assessments_approved_level', to='catalog.referencevalue')),
                ('assessor', models.ForeignKey(help_text='Person conducting assessment; authorised same-tenant reviewer/mentor; cannot be assessed professional.', on_delete=django.db.models.deletion.PROTECT, related_name='competency_assessments_conducted', to='accounts.usertbl')),
                ('previous_authority', models.ForeignKey(help_text='Authority before assessment; AUTHORITY_STATUS snapshot.', on_delete=django.db.models.deletion.PROTECT, related_name='competency_assessments_previous_authority', to='catalog.referencevalue')),
                ('previous_level', models.ForeignKey(help_text='Level before assessment; QUALION_LEVEL snapshot.', on_delete=django.db.models.deletion.PROTECT, related_name='competency_assessments_previous_level', to='catalog.referencevalue')),
                ('recommended_authority', models.ForeignKey(blank=True, help_text='Recommended authority; AUTHORITY_STATUS.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competency_assessments_recommended_authority', to='catalog.referencevalue')),
                ('recommended_level', models.ForeignKey(blank=True, help_text='Assessor recommendation; QUALION_LEVEL.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competency_assessments_recommended_level', to='catalog.referencevalue')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Competency Assessment',
                'verbose_name_plural': 'Competency Assessments',
                'db_table': 'competency_assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_experience_months', models.PositiveIntegerField(default=0, help_text='Non-duplicated calendar experience; union of verified project date intervals for this scope; never manually edited.')),
                ('verified_field_days', models.DecimalField(decimal_places=2, default=0, help_text='Verified actual field exposure; derived from approved ExposureLog.', max_digits=8)),
                ('is_deployable', models.BooleanField(default=False, help_text='Derived from level, authority, valid credentials and compliance.')),
                ('verification_status', models.CharField(choices=[('SELF_DECLARED', 'Self declared'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('PENDING_REVIEW', 'Pending review'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='UNDER_REVIEW', help_text='Competency verification state.', max_length=30)),
                ('effective_from', models.DateField(blank=True, help_text='Effective date of current state.', null=True)),
                ('last_recalculated_at', models.DateTimeField(blank=True, help_text='Updated after experience recalculation.', null=True)),
                ('last_assessed_at', models.DateTimeField(blank=True, help_text='Set after approved assessment.', null=True)),
                ('complexity_rating', models.ForeignKey(blank=True, help_text='Complexity of verified exposure; option_set must be COMPLEXITY; reviewer-assigned.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_scopes_complexity', to='catalog.referencevalue')),
                ('current_authority_status', models.ForeignKey(help_text='Current permitted authority for this scope; option_set must be AUTHORITY_STATUS; default Observer.', on_delete=django.db.models.deletion.PROTECT, related_name='professional_scopes_authority_status', to='catalog.referencevalue')),
                ('current_qualion_level', models.ForeignKey(help_text='Current L0-L5 level for this scope; option_set must be QUALION_LEVEL; default L0.', on_delete=django.db.models.deletion.PROTECT, related_name='professional_scopes_qualion_level', to='catalog.referencevalue')),
            ],
            options={
                'verbose_name': 'Professional Scope',
                'verbose_name_plural': 'Professional Scopes',
                'db_table': 'competency_professional_scope',
                'ordering': ['professional', 'scope'],
            },
        ),
    ]
