# Generated by Django 5.2.11 on 2026-07-31 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('competency', '0001_initial'),
        ('professionals', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalscope',
            name='professional',
            field=models.ForeignKey(help_text='Professional being evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='professionalscope',
            name='scope',
            field=models.ForeignKey(help_text='Industry/scope competency context; global active/retired scope.', on_delete=django.db.models.deletion.PROTECT, related_name='professional_scopes', to='catalog.scopecatalog'),
        ),
        migrations.AddField(
            model_name='professionalscope',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='professional_scope',
            field=models.ForeignKey(help_text='Scope competency being assessed.', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='competency.professionalscope'),
        ),
        migrations.AddConstraint(
            model_name='professionalscope',
            constraint=models.UniqueConstraint(fields=('professional', 'scope'), name='uniq_professional_scope_professional_scope'),
        ),
        migrations.AddConstraint(
            model_name='competencyassessment',
            constraint=models.CheckConstraint(condition=models.Q(('technical_knowledge_score__gte', 0), ('technical_knowledge_score__lte', 100)), name='chk_competency_assessment_technical_score_range'),
        ),
        migrations.AddConstraint(
            model_name='competencyassessment',
            constraint=models.CheckConstraint(condition=models.Q(('field_execution_score__gte', 0), ('field_execution_score__lte', 100)), name='chk_competency_assessment_field_execution_score_range'),
        ),
        migrations.AddConstraint(
            model_name='competencyassessment',
            constraint=models.CheckConstraint(condition=models.Q(('documentation_evidence_score__gte', 0), ('documentation_evidence_score__lte', 100)), name='chk_competency_assessment_documentation_score_range'),
        ),
        migrations.AddConstraint(
            model_name='competencyassessment',
            constraint=models.CheckConstraint(condition=models.Q(('ethics_independence_score__gte', 0), ('ethics_independence_score__lte', 100)), name='chk_competency_assessment_ethics_score_range'),
        ),
        migrations.AddConstraint(
            model_name='competencyassessment',
            constraint=models.CheckConstraint(condition=models.Q(('communication_conduct_score__gte', 0), ('communication_conduct_score__lte', 100)), name='chk_competency_assessment_communication_score_range'),
        ),
        migrations.AddConstraint(
            model_name='competencyassessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'APPROVED'), _negated=True), ('approved_level__isnull', False), _connector='OR'), name='chk_competency_assessment_approved_level_required'),
        ),
        migrations.AddConstraint(
            model_name='competencyassessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'APPROVED'), _negated=True), ('approved_authority__isnull', False), _connector='OR'), name='chk_competency_assessment_approved_authority_required'),
        ),
        migrations.AddConstraint(
            model_name='competencyassessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'REJECTED'), _negated=True), models.Q(('decision_reason', ''), _negated=True), _connector='OR'), name='chk_competency_assessment_decision_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='competencyassessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision__in', ['APPROVED', 'REJECTED']), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='chk_competency_assessment_approved_at_required'),
        ),
    ]
