# Generated by Django 5.2.11 on 2026-09-03 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tenantregistrationinvite'),
        ('competency', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalscope',
            name='current_qualion_level',
            field=models.ForeignKey(blank=True, help_text='Current L0-L5 level for this scope; option_set must be QUALION_LEVEL; default L0.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_scopes_qualion_level', to='catalog.referencevalue'),
        ),
    ]
