# Generated by Django 5.2.11 on 2026-08-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencyassessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'CompetencyAssessment', 'verbose_name_plural': 'CompetencyAssessment'},
        ),
        migrations.AlterModelOptions(
            name='professionalscope',
            options={'ordering': ['professional', 'scope'], 'verbose_name': 'ProfessionalScope', 'verbose_name_plural': 'ProfessionalScope'},
        ),
    ]
