# Generated by Django 5.2.11 on 2026-09-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0002_tenantregistrationinvite'),
        ('competency', '0003_alter_professionalscope_current_qualion_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencyassessment',
            name='assessment_type',
            field=models.CharField(blank=True, choices=[('INITIAL', 'Initial'), ('PERIODIC', 'Periodic'), ('PROGRESSION', 'Progression'), ('AUTHORITY', 'Authority'), ('REVALIDATION', 'Revalidation')], help_text='Assessment purpose.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='assessor',
            field=models.ForeignKey(blank=True, help_text='Person conducting assessment; authorised same-tenant reviewer/mentor; cannot be assessed professional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competency_assessments_conducted', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='assessor_role_snapshot',
            field=models.CharField(blank=True, help_text='Assessor authority snapshot captured at assessment time.', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='communication_conduct_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Communication and professional conduct dimension.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='decision_reason',
            field=models.TextField(blank=True, help_text='Required for rejection or override.', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='documentation_evidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Documentation and evidence quality dimension; threshold may block progression.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='ethics_independence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ethics and independence dimension; threshold may block progression.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='evidence_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Evidence used in assessment; source record IDs and calculated metrics; immutable after decision.', null=True),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='field_execution_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Field execution discipline dimension (0.00-100.00).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='previous_authority',
            field=models.ForeignKey(blank=True, help_text='Authority before assessment; AUTHORITY_STATUS snapshot.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competency_assessments_previous_authority', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='previous_level',
            field=models.ForeignKey(blank=True, help_text='Level before assessment; QUALION_LEVEL snapshot.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competency_assessments_previous_level', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='recommendation',
            field=models.TextField(blank=True, help_text='Assessor recommendation and observations; evidence-based.', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='competencyassessment',
            name='technical_knowledge_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Technical knowledge dimension (0.00-100.00).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='professionalscope',
            name='calendar_experience_months',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Non-duplicated calendar experience; union of verified project date intervals for this scope; never manually edited.', null=True),
        ),
        migrations.AlterField(
            model_name='professionalscope',
            name='current_authority_status',
            field=models.ForeignKey(blank=True, help_text='Current permitted authority for this scope; option_set must be AUTHORITY_STATUS; default Observer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_scopes_authority_status', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='professionalscope',
            name='scope',
            field=models.ForeignKey(blank=True, help_text='Industry/scope competency context; global active/retired scope.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_scopes', to='catalog.scopecatalog'),
        ),
        migrations.AlterField(
            model_name='professionalscope',
            name='verified_field_days',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Verified actual field exposure; derived from approved ExposureLog.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='professionalscope',
            name='verified_project_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Count of distinct VERIFIED ProjectScope rows for this professional+scope; system-managed, never manually edited.', null=True),
        ),
    ]
