# Generated by Django 5.2.11 on 2026-08-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_formfield_options_alter_formmodule_options_and_more'),
        ('competency', '0003_alter_competencyassessment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalscope',
            name='highest_authority_reached',
            field=models.ForeignKey(blank=True, help_text='Highest AUTHORITY_STATUS ever approved for this scope; never decreases, unlike current_authority_status.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_scopes_highest_authority', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='professionalscope',
            name='verified_project_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of distinct VERIFIED ProjectScope rows for this professional+scope; system-managed, never manually edited.'),
        ),
        migrations.AlterField(
            model_name='professionalscope',
            name='is_deployable',
            field=models.CharField(choices=[('DEPLOYABLE', 'Deployable'), ('DEPLOYABLE_WITH_RESTRICTIONS', 'Deployable with restrictions'), ('REVIEW_REQUIRED', 'Review required'), ('NOT_DEPLOYABLE', 'Not deployable')], default='NOT_DEPLOYABLE', help_text='Derived from level, authority, valid credentials and compliance.', max_length=30),
        ),
    ]
