# Generated by Django 5.2.11 on 2026-09-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0004_alter_competencyassessment_assessment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalscope',
            name='current_classification',
            field=models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('CANDIDATE', 'Candidate'), ('MENTOR', 'Mentor')], default='CANDIDATE', max_length=20),
        ),
    ]
