# Generated by Django 5.2.11 on 2026-07-31 07:40

import core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Safe external identifier used in APIs and integrations.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Tenant display name.', max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('legal_name', models.CharField(blank=True, help_text='Registered legal name, when different from display name.', max_length=250)),
                ('code', models.CharField(help_text='Stable internal tenant code.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Use uppercase letters, numbers and underscores only.', regex='^[A-Z0-9_]+$')])),
                ('portal_slug', models.SlugField(help_text='Permanent tenant URL segment used for registration and login.', max_length=80, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Use lowercase letters, numbers and hyphens only.', regex='^[a-z0-9-]+$')])),
                ('custom_domain', models.CharField(blank=True, help_text='Optional tenant-owned domain.', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', help_text='Current tenant lifecycle status.', max_length=20)),
                ('registration_enabled', models.BooleanField(default=True, help_text='Registration endpoint rejects requests when false.')),
                ('login_enabled', models.BooleanField(default=True, help_text='Login endpoint rejects non-platform users when false.')),
                ('default_timezone', models.CharField(help_text='Default timezone used for tenant operations.', max_length=64, validators=[core.validators.validate_iana_timezone])),
                ('default_currency', models.CharField(help_text='Default commercial currency.', max_length=3, validators=[django.core.validators.RegexValidator(code='invalid_currency_code', message='Enter a valid ISO 4217 currency code, e.g. USD.', regex='^[A-Z]{3}$')])),
                ('contact_email', models.EmailField(blank=True, help_text='Primary tenant contact email.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary tenant contact phone.', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a phone number in E.164 format, e.g. +14155552671.', regex='^\\+[1-9]\\d{6,14}$')])),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Feature flags and non-sensitive tenant configuration.')),
                ('branding', models.JSONField(blank=True, default=dict, help_text='Tenant branding configuration (logo, colours, display settings).')),
                ('created_by', models.ForeignKey(help_text='User who created the tenant. Must be the Platform Super Admin.', on_delete=django.db.models.deletion.PROTECT, related_name='tenants_created', to='accounts.usertbl')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenancy_tenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Safe external identifier used in APIs and integrations.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_type', models.CharField(choices=[('BRANCH', 'Branch'), ('DEPARTMENT', 'Department'), ('OPERATING_UNIT', 'Operating unit'), ('CLIENT', 'Client'), ('EMPLOYER', 'Employer'), ('COLLEGE', 'College'), ('TRAINING_PROVIDER', 'Training provider'), ('CERTIFICATION_BODY', 'Certification body'), ('VERIFICATION_AGENCY', 'Verification agency'), ('MANUFACTURER', 'Manufacturer'), ('EPC_CONTRACTOR', 'EPC contractor'), ('SHIPYARD', 'Shipyard'), ('CLASSIFICATION_SOCIETY', 'Classification society'), ('OTHER', 'Other')], help_text='Business type of the organisation.', max_length=40)),
                ('name', models.CharField(help_text='Display name.', max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('legal_name', models.CharField(blank=True, help_text='Legal name.', max_length=250)),
                ('code', models.CharField(blank=True, help_text='Tenant-specific organisation/unit code. Unique within tenant when populated.', max_length=60, null=True)),
                ('country_code', models.CharField(blank=True, help_text='Country location.', max_length=2, validators=[django.core.validators.RegexValidator(code='invalid_country_code', message='Enter a valid ISO 3166-1 alpha-2 country code, e.g. AE.', regex='^[A-Z]{2}$')])),
                ('city', models.CharField(blank=True, help_text='City location.', max_length=120)),
                ('website', models.URLField(blank=True, help_text='Organisation website.', max_length=500)),
                ('email', models.EmailField(blank=True, help_text='Organisation contact email.', max_length=254)),
                ('external_reference', models.CharField(blank=True, db_index=True, help_text='External system/import identifier. Unique only when the integration requires it.', max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Non-sensitive organisation-specific attributes only.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive records cannot be selected for new assignments.')),
                ('industry', models.ForeignKey(blank=True, help_text='Primary industry associated with the organisation/unit. When populated, option_set must be INDUSTRY.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='catalog.referencevalue')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent branch, department or organisation. Same tenant; cannot reference self; hierarchy cycle check required.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tenancy.organization')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns the organisation record.', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'tenancy_organization',
                'ordering': ['tenant', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('tenant', 'code'), name='uniq_organization_tenant_code'), models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='chk_organization_parent_not_self')],
            },
        ),
        migrations.CreateModel(
            name='TenantOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(help_text='Country of operation.', max_length=2, validators=[django.core.validators.RegexValidator(code='invalid_country_code', message='Enter a valid ISO 3166-1 alpha-2 country code, e.g. AE.', regex='^[A-Z]{2}$')])),
                ('region_name', models.CharField(blank=True, help_text='Optional state, province or region.', max_length=120)),
                ('is_registration_enabled', models.BooleanField(default=True, help_text='Only enabled operations appear during registration.')),
                ('is_active', models.BooleanField(default=True, help_text='Operational status.')),
                ('effective_from', models.DateField(blank=True, help_text='Date on which the operation becomes valid.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Optional end date.', null=True)),
                ('created_by', models.ForeignKey(help_text='User who assigned the operation. Must be Platform Super Admin.', on_delete=django.db.models.deletion.PROTECT, related_name='tenant_operations_created', to='accounts.usertbl')),
                ('industry', models.ForeignKey(help_text='Industry in which the tenant operates. ReferenceValue.option_set must be INDUSTRY and active.', on_delete=django.db.models.deletion.PROTECT, related_name='tenant_operations', to='catalog.referencevalue')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this operating permission.', on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Operation',
                'verbose_name_plural': 'Tenant Operations',
                'db_table': 'tenancy_tenant_operation',
                'ordering': ['tenant', 'industry', 'country_code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'industry', 'country_code'), name='uniq_tenant_operation_tenant_industry_country'), models.CheckConstraint(condition=models.Q(('effective_from__isnull', True), ('effective_to__isnull', True), ('effective_from__lte', models.F('effective_to')), _connector='OR'), name='chk_tenant_operation_effective_from_before_to')],
            },
        ),
    ]
