"""
Hand-written migration — not generated by makemigrations.

Fixes schema drift caused by tenancy/migrations/0001_initial.py having
been rewritten after it was already applied to some databases.

This migration is intentionally database-independent and supports both
SQLite and MySQL.

Three kinds of drift are handled:

1. Missing tenancy tables
   - Creates missing tables from the current historical model state using
     schema_editor.create_model().
   - Uses multiple passes so FK dependencies can resolve naturally.

2. Tenant missing columns
   - Adds the nine fields that may be missing from older databases.

3. TenantOperation schema drift
   - Older databases may have:
       created_by
   - Current model expects:
       requested_by
       status
       reviewed_by
       reviewed_at
       rejection_reason

   Instead of rebuilding the table with raw SQLite/MySQL SQL, this
   migration adds the missing columns using Django's schema_editor.
   Existing created_by_id values are copied to requested_by_id when
   possible.

4. Organization missing columns
   - Adds legal_entity and owner when missing.

The migration is idempotent:
- If the table/column already exists, nothing is done.
- If the database already matches the current schema, this is a no-op.

IMPORTANT:
This migration intentionally does not remove legacy columns such as
created_by_id. Keeping an old column is safer than dropping it during a
data-preserving drift repair.
"""

from django.db import migrations


def fix_drift(apps, schema_editor):
    Tenant = apps.get_model("tenancy", "Tenant")
    TenantOperation = apps.get_model("tenancy", "TenantOperation")
    Organization = apps.get_model("tenancy", "Organization")

    connection = schema_editor.connection

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def table_exists(table_name):
        """
        Database-independent table existence check.

        Works with:
        - MySQL
        - SQLite
        - PostgreSQL
        """
        return table_name in connection.introspection.table_names()

    def get_columns(table_name):
        """
        Return actual database column names for a table.
        """
        if not table_exists(table_name):
            return set()

        with connection.cursor() as cursor:
            description = connection.introspection.get_table_description(
                cursor,
                table_name,
            )

        return {column.name for column in description}

    def add_field_if_missing(model, field_name):
        """
        Add a model field only when its database column is missing.
        """
        table_name = model._meta.db_table
        actual_columns = get_columns(table_name)

        field = model._meta.get_field(field_name)

        if field.column not in actual_columns:
            schema_editor.add_field(model, field)

    # ------------------------------------------------------------------
    # 1. Create missing tenancy tables
    # ------------------------------------------------------------------

    tenancy_models = list(
        apps.app_configs["tenancy"].get_models()
    )

    missing = [
        model
        for model in tenancy_models
        if not table_exists(model._meta.db_table)
    ]

    progress = True

    while missing and progress:
        progress = False
        still_missing = []

        for model in missing:
            try:
                schema_editor.create_model(model)
                progress = True

            except Exception:
                # Usually caused by a FK dependency whose table has not
                # been created yet. Try this model again in the next pass.
                still_missing.append(model)

        missing = still_missing

    if missing:
        raise RuntimeError(
            "Could not create tenancy tables after resolving FK "
            "dependencies: "
            + ", ".join(
                model._meta.db_table
                for model in missing
            )
        )

    # ------------------------------------------------------------------
    # 2. Tenant: add missing fields
    # ------------------------------------------------------------------

    tenant_fields = (
        "description",
        "industry_ids",
        "organisation_type",
        "parent_tenant",
        "service_scope_ids",
        "status_reason",
        "trade_name",
        "website",
        "workspace_type",
    )

    for field_name in tenant_fields:
        add_field_if_missing(
            Tenant,
            field_name,
        )

    # ------------------------------------------------------------------
    # 3. TenantOperation schema drift
    # ------------------------------------------------------------------

    op_table = TenantOperation._meta.db_table
    op_columns = get_columns(op_table)

    if op_table:
        # --------------------------------------------------------------
        # Older schema:
        #
        #     created_by_id
        #
        # Current schema:
        #
        #     requested_by_id
        #     reviewed_by_id
        #     reviewed_at
        #     status
        #     rejection_reason
        #
        # Add only missing current fields.
        # --------------------------------------------------------------

        if "requested_by_id" not in op_columns:
            add_field_if_missing(
                TenantOperation,
                "requested_by",
            )

        if "reviewed_by_id" not in op_columns:
            add_field_if_missing(
                TenantOperation,
                "reviewed_by",
            )

        if "reviewed_at" not in op_columns:
            add_field_if_missing(
                TenantOperation,
                "reviewed_at",
            )

        if "status" not in op_columns:
            add_field_if_missing(
                TenantOperation,
                "status",
            )

        if "rejection_reason" not in op_columns:
            add_field_if_missing(
                TenantOperation,
                "rejection_reason",
            )

        # --------------------------------------------------------------
        # Copy legacy created_by_id -> requested_by_id
        #
        # Only do this when both columns exist.
        # --------------------------------------------------------------

        op_columns = get_columns(op_table)

        if (
            "created_by_id" in op_columns
            and "requested_by_id" in op_columns
        ):
            with connection.cursor() as cursor:
                cursor.execute(
                    f"""
                    UPDATE {op_table}
                    SET requested_by_id = created_by_id
                    WHERE requested_by_id IS NULL
                      AND created_by_id IS NOT NULL
                    """
                )

        # --------------------------------------------------------------
        # Existing records from the old schema represented active
        # operations. Set their new status accordingly.
        #
        # Only update rows where status is still the default PENDING.
        # --------------------------------------------------------------

        if "status" in op_columns:
            with connection.cursor() as cursor:
                cursor.execute(
                    f"""
                    UPDATE {op_table}
                    SET status = 'ACTIVE'
                    WHERE status = 'PENDING'
                    """
                )

    # ------------------------------------------------------------------
    # 4. Organization: add missing nullable FK columns
    # ------------------------------------------------------------------

    for field_name in (
        "legal_entity",
        "owner",
    ):
        add_field_if_missing(
            Organization,
            field_name,
        )


def noop_reverse(apps, schema_editor):
    """
    This is a data-preserving drift repair.

    We intentionally do not reverse it because:
    - tables may contain production data
    - columns may have been populated after this migration
    - deleting them would be destructive
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
        ("accounts", "0002_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            fix_drift,
            noop_reverse,
        ),
    ]