"""Hand-written migration — not generated by makemigrations.

Same root cause as the catalog/professionals/experience/governance drift
fixes elsewhere in this project: tenancy/migrations/0001_initial.py was
massively rewritten in place (the entire Stage 1 tenant onboarding
blueprint — TenantLegalEntity, TenantLocation, TenantAuthorisedRepresentative,
TenantVerification, TenantDocument, TenantLegalAcceptance, and ~35 other
models — was added to it) after it had already been applied to some
databases under that same name. Since the applied-migration ledger only
tracks names, `migrate` never re-ran it and `makemigrations` sees no diff
against the current (already-rewritten) file — so this had to be detected
by comparing live schema against current models directly, not through
either normal command.

Three kinds of gap, each handled differently:
  1. ~41 whole tables never created at all -> created directly from the
     current model classes via schema_editor.create_model(), in a
     multi-pass loop so FK dependency order resolves itself regardless of
     model definition order.
  2. Tenant gained 9 new nullable columns -> plain ADD COLUMN.
  3. TenantOperation was restructured (created_by -> requested_by, plus
     status/reviewed_by/reviewed_at/rejection_reason added) -> rebuilt via
     the same create-new-copy-drop-rename pattern as the catalog fix,
     since SQLite can't ALTER a column's underlying meaning in place.
     Organization gained 2 new nullable FK columns -> plain ADD COLUMN.

Only acts when a table/column is actually missing — a no-op on any
database that only ever saw the current (already-rewritten) file content.
"""

from django.db import migrations


def fix_drift(apps, schema_editor):
    Tenant = apps.get_model("tenancy", "Tenant")
    TenantOperation = apps.get_model("tenancy", "TenantOperation")
    Organization = apps.get_model("tenancy", "Organization")
    tenancy_models = list(apps.app_configs["tenancy"].get_models())

    with schema_editor.connection.cursor() as cursor:
        def table_exists(table):
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name=%s",
                [table],
            )
            return cursor.fetchone() is not None

        def columns(table):
            cursor.execute(f"PRAGMA table_info({table})")
            return {row[1] for row in cursor.fetchall()}

        # --- 1. Missing tables ---
        missing = [m for m in tenancy_models if not table_exists(m._meta.db_table)]
        progress = True
        while missing and progress:
            progress = False
            still_missing = []
            for model in missing:
                try:
                    schema_editor.create_model(model)
                    progress = True
                except Exception:
                    still_missing.append(model)
            missing = still_missing
        if missing:
            raise RuntimeError(
                "Could not create tenancy tables (unresolved FK dependency "
                "order): " + ", ".join(m._meta.db_table for m in missing)
            )

        # --- 2. Tenant: new nullable columns ---
        tenant_table = Tenant._meta.db_table
        tenant_actual = columns(tenant_table)
        for field_name in (
            "description", "industry_ids", "organisation_type", "parent_tenant",
            "service_scope_ids", "status_reason", "trade_name", "website", "workspace_type",
        ):
            field = Tenant._meta.get_field(field_name)
            if field.column not in tenant_actual:
                if field.get_internal_type() == "JSONField":
                    cursor.execute(
                        f"ALTER TABLE {tenant_table} ADD COLUMN {field.column} text DEFAULT '[]'"
                    )
                else:
                    schema_editor.add_field(Tenant, field)

        # --- 3. TenantOperation: rebuild if still in the old shape ---
        op_table = TenantOperation._meta.db_table
        op_actual = columns(op_table)
        if "status" not in op_actual and "created_by_id" in op_actual:
            cursor.execute(
                """
                CREATE TABLE tenancy_tenant_operation_new (
                  id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                  created_at datetime NOT NULL,
                  updated_at datetime NOT NULL,
                  country_code varchar(2) NULL,
                  region_name varchar(120) NULL,
                  status varchar(20) NOT NULL DEFAULT 'PENDING',
                  is_registration_enabled bool NOT NULL,
                  is_active bool NOT NULL,
                  effective_from date NULL,
                  effective_to date NULL,
                  rejection_reason text NOT NULL DEFAULT '',
                  requested_by_id bigint NULL REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED,
                  reviewed_by_id bigint NULL REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED,
                  reviewed_at datetime NULL,
                  industry_id bigint NOT NULL REFERENCES catalog_reference_value (id) DEFERRABLE INITIALLY DEFERRED,
                  tenant_id bigint NOT NULL REFERENCES tenancy_tenant (id) DEFERRABLE INITIALLY DEFERRED,
                  CONSTRAINT uniq_tenant_operation_tenant_industry_country UNIQUE (tenant_id, industry_id, country_code),
                  CONSTRAINT chk_tenant_operation_dates CHECK (effective_from IS NULL OR effective_to IS NULL OR effective_from <= effective_to)
                )
                """
            )
            cursor.execute(
                """
                INSERT INTO tenancy_tenant_operation_new
                  (id, created_at, updated_at, country_code, region_name, status, is_registration_enabled, is_active,
                   effective_from, effective_to, rejection_reason, requested_by_id, reviewed_by_id, reviewed_at, industry_id, tenant_id)
                SELECT
                  id, created_at, updated_at, country_code, region_name, 'ACTIVE', is_registration_enabled, is_active,
                  effective_from, effective_to, '', created_by_id, NULL, NULL, industry_id, tenant_id
                FROM tenancy_tenant_operation
                """
            )
            cursor.execute("DROP TABLE tenancy_tenant_operation")
            cursor.execute("ALTER TABLE tenancy_tenant_operation_new RENAME TO tenancy_tenant_operation")
            cursor.execute("CREATE INDEX tenancy_tenant_operation_tenant_id_idx ON tenancy_tenant_operation (tenant_id)")
            cursor.execute("CREATE INDEX tenancy_tenant_operation_industry_id_idx ON tenancy_tenant_operation (industry_id)")

        # --- 4. Organization: new nullable FK columns ---
        org_table = Organization._meta.db_table
        org_actual = columns(org_table)
        for field_name in ("legal_entity", "owner"):
            field = Organization._meta.get_field(field_name)
            if field.column not in org_actual:
                schema_editor.add_field(Organization, field)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
        ("accounts", "0002_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fix_drift, noop_reverse),
    ]
