# Generated by Django 5.2.4 on 2026-08-03 07:11

import core.validators
import tenancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Tenant logo image. Max size 10MB.', max_length=1000, null=True, upload_to=tenancy.models.tenant_logo_upload_path, validators=[core.validators.MaxFileSizeValidator(10485760)]),
        ),
    ]
