# Generated by Django 5.2.11 on 2026-09-05 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_formfield_data_type'),
        ('tenancy', '0002_fix_schema_drift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='Must be an Organization row with organization_type in BRANCH/DEPARTMENT/OPERATING_UNIT — enforce in clean().', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_business_units', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_industry', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_locations', to='tenancy.tenantlocation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope_catalog_entries',
            field=models.ManyToManyField(blank=True, related_name='projects_scopes', to='catalog.scopecatalog'),
        ),
    ]
