# Generated by Django 5.2.11 on 2026-08-24 08:09

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_consentrecord_options_and_more'),
        ('catalog', '0002_alter_formfield_options_alter_formmodule_options_and_more'),
        ('tenancy', '0002_module_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tenantoperation',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='tenantoperation',
            name='uniq_tenant_operation_tenant_industry_country',
        ),
        migrations.RemoveConstraint(
            model_name='tenantoperation',
            name='chk_tenant_operation_effective_from_before_to',
        ),
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, help_text='Max 2000 chars per blueprint.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('PMC', 'PMC'), ('EPC', 'EPC Contractor'), ('MANUFACTURER', 'Manufacturer'), ('INSPECTION_BODY', 'Inspection Body'), ('SHIPOWNER', 'Shipowner'), ('OPERATOR', 'Operator'), ('TRAINING_ORG', 'Training Organisation'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='parent_tenant',
            field=models.ForeignKey(blank=True, help_text='tenant.parent_tenant_id â€” group hierarchy.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_tenants', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='service_scope_ids',
            field=models.JSONField(blank=True, default=list, help_text='tenant.service_scope_ids cache â€” see TenantScope for the authoritative rows.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status_reason',
            field=models.TextField(blank=True, help_text='Required when status changes to RESTRICTED/SUSPENDED/ARCHIVED/CLOSED â€” enforce in serializer/service layer.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trade_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='workspace_type',
            field=models.CharField(blank=True, choices=[('ORGANISATION', 'Organisation tenant'), ('PERSONAL', 'Personal workspace')], help_text='tenant.workspace_type â€” personal workspaces get no organisational privileges.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, help_text='City location.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country_code',
            field=models.CharField(blank=True, help_text='Country location.', max_length=2, null=True, validators=[django.core.validators.RegexValidator(code='invalid_country_code', message='Enter a valid ISO 3166-1 alpha-2 country code, e.g. AE.', regex='^[A-Z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, help_text='Organisation contact email.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Legal name.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Non-sensitive organisation-specific attributes only.', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, help_text='Display name.', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('BRANCH', 'Branch'), ('DEPARTMENT', 'Department'), ('OPERATING_UNIT', 'Operating unit'), ('CLIENT', 'Client'), ('EMPLOYER', 'Employer'), ('COLLEGE', 'College'), ('TRAINING_PROVIDER', 'Training provider'), ('CERTIFICATION_BODY', 'Certification body'), ('VERIFICATION_AGENCY', 'Verification agency'), ('MANUFACTURER', 'Manufacturer'), ('EPC_CONTRACTOR', 'EPC contractor'), ('SHIPYARD', 'Shipyard'), ('CLASSIFICATION_SOCIETY', 'Classification society'), ('OTHER', 'Other')], help_text='Business type of the organisation.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='Organisation website.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='branding',
            field=models.JSONField(blank=True, default=dict, help_text='Tenant branding configuration (logo, colours, display settings).', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.CharField(blank=True, help_text='Stable internal tenant code.', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Use uppercase letters, numbers and underscores only.', regex='^[A-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary tenant contact email.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary tenant contact phone.', max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a phone number in E.164 format, e.g. +14155552671.', regex='^\\+[1-9]\\d{6,14}$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants_created', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='default_currency',
            field=models.CharField(blank=True, help_text='Default commercial currency.', max_length=3, null=True, validators=[django.core.validators.RegexValidator(code='invalid_currency_code', message='Enter a valid ISO 4217 currency code, e.g. USD.', regex='^[A-Z]{3}$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='default_timezone',
            field=models.CharField(blank=True, help_text='Default timezone used for tenant operations.', max_length=64, null=True, validators=[core.validators.validate_iana_timezone]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Registered legal name, when different from display name.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(blank=True, help_text='Tenant display name.', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='portal_slug',
            field=models.SlugField(blank=True, help_text='Permanent tenant URL segment used for registration and login.', max_length=80, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Use lowercase letters, numbers and hyphens only.', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Feature flags and non-sensitive tenant configuration.', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('RESTRICTED', 'Restricted'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', help_text='Current tenant lifecycle status.', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantoperation',
            name='country_code',
            field=models.CharField(blank=True, help_text='Country of operation.', max_length=2, null=True, validators=[django.core.validators.RegexValidator(code='invalid_country_code', message='Enter a valid ISO 3166-1 alpha-2 country code, e.g. AE.', regex='^[A-Z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='tenantoperation',
            name='region_name',
            field=models.CharField(blank=True, help_text='Optional state, province or region.', max_length=120, null=True),
        ),
        migrations.AddConstraint(
            model_name='tenantoperation',
            constraint=models.UniqueConstraint(fields=('tenant', 'industry', 'country_code'), name='uniq_tenant_operation'),
        ),
        migrations.AddConstraint(
            model_name='tenantoperation',
            constraint=models.CheckConstraint(check=models.Q(('effective_from__isnull', True), ('effective_to__isnull', True), ('effective_from__lte', models.F('effective_to')), _connector='OR'), name='chk_tenant_operation_dates'),
        ),
    ]
