# Generated by Django 5.2.11 on 2026-08-26 10:14

import core.validators
import django.core.validators
import django.db.models.deletion
import tenancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_consentrecord_options_and_more'),
        ('catalog', '0002_alter_formfield_options_alter_formmodule_options_and_more'),
        ('experience', '0005_alter_employmentrecord_options_and_more'),
        ('tenancy', '0003_alter_organization_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantbusinessunit',
            name='legal_entity',
        ),
        migrations.RemoveField(
            model_name='tenantbusinessunit',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tenantbusinessunit',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='project',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='Must be an Organization row with organization_type in BRANCH/DEPARTMENT/OPERATING_UNIT — enforce in clean().', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='tenantlocation',
            name='business_unit',
            field=models.ForeignKey(blank=True, help_text='Must be an Organization row with organization_type in BRANCH/DEPARTMENT/OPERATING_UNIT — enforce in clean().', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='tenancy.organization'),
        ),
        migrations.RemoveField(
            model_name='tenantindustry',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='tenantindustry',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantmembership',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='tenantmembership',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectmembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='tenantroleassignment',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='tenantresumetemplate',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantscope',
            name='scope_catalog',
        ),
        migrations.RemoveField(
            model_name='tenantscope',
            name='tenant',
        ),
        migrations.RemoveConstraint(
            model_name='projectmembership',
            name='uniq_project_membership',
        ),
        migrations.RemoveConstraint(
            model_name='tenantoperation',
            name='uniq_tenant_operation',
        ),
        migrations.RemoveField(
            model_name='conflictofinterestdeclaration',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='dataexportrequest',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='projectrequirementscope',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantapprovalmatrix',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantbilling',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantbranding',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantintegration',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantinvitation',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantlegalacceptance',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantlegalsettings',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantmoduleentitlement',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantnda',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantnotificationsettings',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantnumberingconfig',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantoperation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tenantoperationlog',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantreporttemplate',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantsecuritysettings',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantterminology',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantverification',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='tenantworkflow',
            name='public_id',
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_entity',
            field=models.ForeignKey(blank=True, help_text='Which legal entity this internal division sits under, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_units', to='tenancy.tenantlegalentity'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Required in practice for BRANCH/DEPARTMENT/OPERATING_UNIT rows (sheet 19 tenant_business_units.owner); optional for external org types.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='industry_ids',
            field=models.JSONField(blank=True, default=list, help_text='tenant.industry_ids — list of catalog.ReferenceValue codes (option_type=INDUSTRY).', null=True),
        ),
        migrations.AddField(
            model_name='tenantlegalentity',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantlegalentity',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entities_requested', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='tenantlegalentity',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantlegalentity',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_entities_reviewed', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='tenantlegalentity',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantoperation',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantoperation',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_operations_requested', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='tenantoperation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantoperation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_operations_reviewed', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='tenantoperation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantreporttemplate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantreporttemplate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates_reviewed', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='tenantroleassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_role_assignments', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(code='invalid_country_code', message='Enter a valid ISO 3166-1 alpha-2 country code, e.g. AE.', regex='^[A-Z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('BRANCH', 'Branch'), ('DEPARTMENT', 'Department'), ('OPERATING_UNIT', 'Operating unit'), ('CLIENT', 'Client'), ('EMPLOYER', 'Employer'), ('COLLEGE', 'College'), ('TRAINING_PROVIDER', 'Training provider'), ('CERTIFICATION_BODY', 'Certification body'), ('VERIFICATION_AGENCY', 'Verification agency'), ('MANUFACTURER', 'Manufacturer'), ('EPC_CONTRACTOR', 'EPC contractor'), ('SHIPYARD', 'Shipyard'), ('CLASSIFICATION_SOCIETY', 'Classification society'), ('OTHER', 'Other')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectplacement',
            name='professional_assignment',
            field=models.ForeignKey(blank=True, help_text="Link to the candidate's own experience.ProfessionalAssignment row (assignment_type=PROJECT) once confirmed.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_placement', to='experience.professionalassignment'),
        ),
        migrations.AlterField(
            model_name='projectrequirement',
            name='role_code',
            field=models.ForeignKey(help_text='option_set.option_type=PROFESSIONAL_ROLE, matching professionals.ProfessionalProfile.primary_role.', on_delete=django.db.models.deletion.PROTECT, related_name='project_requirements', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='branding',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.CharField(blank=True, help_text='tenant.tenant_code — stable internal reference, never the company name.', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Use uppercase letters, numbers and underscores only.', regex='^[A-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a phone number in E.164 format, e.g. +14155552671.', regex='^\\+[1-9]\\d{6,14}$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants_created', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='default_currency',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(code='invalid_currency_code', message='Enter a valid ISO 4217 currency code, e.g. USD.', regex='^[A-Z]{3}$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='default_timezone',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[core.validators.validate_iana_timezone]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='login_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=tenancy.models.tenant_logo_upload_path, validators=[core.validators.MaxFileSizeValidator(10485760)]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='parent_tenant',
            field=models.ForeignKey(blank=True, help_text='tenant.parent_tenant_id — group hierarchy.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_tenants', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='portal_slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Use lowercase letters, numbers and hyphens only.', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='registration_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='service_scope_ids',
            field=models.JSONField(blank=True, default=list, help_text='tenant.service_scope_ids — list of catalog.ScopeCatalog codes.', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('RESTRICTED', 'Restricted'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status_reason',
            field=models.TextField(blank=True, help_text='Required when status changes to RESTRICTED/SUSPENDED/ARCHIVED/CLOSED — enforce in serializer/service layer.', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='workspace_type',
            field=models.CharField(blank=True, choices=[('ORGANISATION', 'Organisation tenant'), ('PERSONAL', 'Personal workspace')], help_text='tenant.workspace_type — personal workspaces get no organisational privileges.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenantoperation',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(code='invalid_country_code', message='Enter a valid ISO 3166-1 alpha-2 country code, e.g. AE.', regex='^[A-Z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='tenantoperation',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantoperation',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantoperation',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_operations', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='tenantoperation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenantoperation',
            name='is_registration_enabled',
            field=models.BooleanField(default=True, help_text='Only takes effect once status=ACTIVE. Lets the tenant pause/resume registration in an already-approved industry+country without re-requesting approval.'),
        ),
        migrations.AlterField(
            model_name='tenantoperation',
            name='region_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='tenantoperation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantroleassignment',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_roles_granted', to='accounts.usertbl'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uniq_project_membership'),
        ),
        migrations.AddConstraint(
            model_name='tenantoperation',
            constraint=models.UniqueConstraint(fields=('tenant', 'industry', 'country_code'), name='uniq_tenant_operation_tenant_industry_country'),
        ),
        migrations.DeleteModel(
            name='TenantBusinessUnit',
        ),
        migrations.DeleteModel(
            name='TenantIndustry',
        ),
        migrations.DeleteModel(
            name='TenantMembership',
        ),
        migrations.DeleteModel(
            name='TenantResumeTemplate',
        ),
        migrations.DeleteModel(
            name='TenantScope',
        ),
    ]
