# Generated by Django 5.2.11 on 2026-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='profile_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('STAGE1_COMPLETE', 'Stage 1 complete'), ('STAGE2_INCOMPLETE', 'Stage 2 incomplete'), ('SUBMITTED', 'Submitted'), ('STAGE2_SUBMITTED', 'Stage 2 submitted'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', help_text='Current profile workflow status.', max_length=30),
        ),
    ]
