# Generated by Django 5.2.11 on 2026-08-01 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_remove_evidencedocument_file_hash_and_more'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='existing_resume',
            field=models.ForeignKey(blank=True, help_text='Optional professional resume. Evidence type must be RESUME and same professional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profiles_resume', to='evidence.evidencedocument'),
        ),
    ]
