# Generated by Django 5.2.11 on 2026-08-26 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0001_initial'),
        ('evidence', '0002_initial'),
        ('experience', '0002_initial'),
        ('professionals', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityrecord',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Structured organisation reference.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_records', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='issuing_organization',
            field=models.ForeignKey(blank=True, help_text='Structured issuing body. Same tenant; type should match record context where known.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credentials_issued', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='primary_evidence',
            field=models.ForeignKey(blank=True, help_text='Primary supporting document. Must belong to same professional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_records_primary', to='evidence.evidencedocument'),
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='related_industry',
            field=models.ForeignKey(blank=True, help_text='Related technical industry; used when credential supports a specific industry.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='related_project',
            field=models.ForeignKey(blank=True, help_text='Related project; used for client approvals. Same tenant/professional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='experience.projectrecord'),
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='related_scope',
            field=models.ForeignKey(blank=True, help_text='Related technical scope; used when credential supports a specific scope.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='catalog.scopecatalog'),
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='credentialrecorditem',
            name='credential_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='professionals.credentialrecord'),
        ),
        migrations.AddField(
            model_name='credentialrecorditem',
            name='evidence_document',
            field=models.ForeignKey(blank=True, help_text='Supporting document for the item. Must belong to same professional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_record_items', to='evidence.evidencedocument'),
        ),
        migrations.AddField(
            model_name='credentialrecorditem',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='availability_status',
            field=models.ForeignKey(blank=True, help_text='Current availability. option_set must be AVAILABILITY_STATUS.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_profiles_availability', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='classified_by',
            field=models.ForeignKey(blank=True, help_text='User who confirmed classification. Tenant Admin, Reviewer or Platform Super Admin; cannot be profile owner.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professionals_classified', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='existing_resume',
            field=models.ForeignKey(blank=True, help_text='Optional professional resume. Evidence type must be RESUME and same professional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profiles_resume', to='evidence.evidencedocument'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='gender',
            field=models.ForeignKey(blank=True, help_text='Optional gender value. option_set must be GENDER.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_profiles_gender', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='highest_qualification_level',
            field=models.ForeignKey(blank=True, help_text='Highest qualification selected at Stage 1. option_set must be QUALIFICATION_LEVEL.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_profiles_qualification_level', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='primary_industry',
            field=models.ForeignKey(blank=True, help_text='Primary industry selected during registration. Must be active INDUSTRY permitted by TenantOperation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_profiles_primary_industry', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='primary_role',
            field=models.ForeignKey(blank=True, help_text='Primary professional role. option_set must be PROFESSIONAL_ROLE.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_profiles_primary_role', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='primary_scope',
            field=models.ForeignKey(blank=True, help_text='Primary inspection/survey scope. Scope.industry must equal primary_industry.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_profiles_primary_scope', to='catalog.scopecatalog'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='profile_photo_evidence',
            field=models.ForeignKey(blank=True, help_text='Optional professional photograph. Evidence type must be PHOTOGRAPH and same professional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profiles_photo', to='evidence.evidencedocument'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='rate_type',
            field=models.ForeignKey(blank=True, help_text='Expected rate basis. option_set must be RATE_TYPE.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_profiles_rate_type', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='registration_application',
            field=models.OneToOneField(help_text='Registration application that created the profile. Must refer to the same tenant and user.', on_delete=django.db.models.deletion.PROTECT, related_name='professional_profile', to='accounts.registrationapplication'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='self_declared_career_stage',
            field=models.ForeignKey(blank=True, help_text='Self-declared career stage used only for initial routing. option_set must be CAREER_STAGE.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_profiles_career_stage', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='user',
            field=models.OneToOneField(help_text='Authentication account for the professional. Unique with tenant; user role must include PROFESSIONAL.', on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='professional',
            field=models.ForeignKey(help_text='Professional who owns the record.', on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='professional',
            field=models.ForeignKey(help_text='Professional who owns the contact.', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='capabilityrecord',
            name='professional',
            field=models.ForeignKey(help_text='Professional who owns the capability.', on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='professionalreview',
            name='professional',
            field=models.ForeignKey(help_text='Professional being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='professionalreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Decision maker. Tenant Admin/Reviewer or Platform Super Admin; cannot be profile owner.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_reviews_decided', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='professionalreview',
            name='submitted_by',
            field=models.ForeignKey(help_text='User who submitted the review request. Usually profile owner.', on_delete=django.db.models.deletion.PROTECT, related_name='professional_reviews_submitted', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='professionalreview',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddConstraint(
            model_name='professionalprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='uniq_professional_profile_tenant_user'),
        ),
        migrations.AddConstraint(
            model_name='professionalprofile',
            constraint=models.CheckConstraint(condition=models.Q(('completion_percent__gte', 0), ('completion_percent__lte', 100)), name='chk_professional_profile_completion_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='professionalprofile',
            constraint=models.CheckConstraint(condition=models.Q(('notice_period_days__isnull', True), models.Q(('notice_period_days__gte', 0), ('notice_period_days__lte', 365)), _connector='OR'), name='chk_professional_profile_notice_period_range'),
        ),
        migrations.AddConstraint(
            model_name='professionalprofile',
            constraint=models.CheckConstraint(condition=models.Q(('expected_rate__isnull', True), models.Q(('rate_currency', ''), _negated=True), _connector='OR'), name='chk_professional_profile_rate_currency_required'),
        ),
        migrations.AddConstraint(
            model_name='professionalprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('address_line_1', ''), ('address_line_2', ''), ('postal_code', '')), models.Q(('address_country_code', ''), _negated=True), _connector='OR'), name='chk_professional_profile_address_country_required'),
        ),
        migrations.AddConstraint(
            model_name='professionalprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('classification_status', 'CONFIRMED'), _negated=True), ('classified_at__isnull', False), _connector='OR'), name='chk_professional_profile_classified_at_required'),
        ),
        migrations.AddConstraint(
            model_name='professionalprofile',
            constraint=models.CheckConstraint(condition=models.Q(('classified_by', models.F('user')), _negated=True), name='chk_professional_profile_classified_by_not_owner'),
        ),
        migrations.AddConstraint(
            model_name='credentialrecord',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='chk_credential_record_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='credentialrecord',
            constraint=models.CheckConstraint(condition=models.Q(('issue_date__isnull', True), ('expiry_date__isnull', True), ('issue_date__lte', models.F('expiry_date')), _connector='OR'), name='chk_credential_record_issue_before_expiry'),
        ),
        migrations.AddConstraint(
            model_name='credentialrecord',
            constraint=models.CheckConstraint(condition=models.Q(('issuing_organization__isnull', False), models.Q(('issuing_body_snapshot', ''), _negated=True), _connector='OR'), name='chk_credential_record_issuing_body_required'),
        ),
        migrations.AddConstraint(
            model_name='contactrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('email', ''), _negated=True), models.Q(('phone', ''), _negated=True), _connector='OR'), name='chk_contact_record_email_or_phone_required'),
        ),
        migrations.AddConstraint(
            model_name='contactrecord',
            constraint=models.CheckConstraint(condition=models.Q(('consent_given', False), ('consent_given_at__isnull', False), _connector='OR'), name='chk_contact_record_consent_given_at_required'),
        ),
        migrations.AddConstraint(
            model_name='capabilityrecord',
            constraint=models.CheckConstraint(condition=models.Q(('reference_value__isnull', False), models.Q(('custom_name', ''), _negated=True), _connector='OR'), name='chk_capability_record_custom_name_required'),
        ),
        migrations.AddConstraint(
            model_name='capabilityrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('capability_type', 'LANGUAGE'), _negated=True), models.Q(models.Q(('speaking_level', ''), _negated=True), models.Q(('reading_level', ''), _negated=True), models.Q(('writing_level', ''), _negated=True)), _connector='OR'), name='chk_capability_record_language_levels_required'),
        ),
        migrations.AddConstraint(
            model_name='capabilityrecord',
            constraint=models.CheckConstraint(condition=models.Q(('years_experience__isnull', True), ('years_experience__gte', 0), _connector='OR'), name='chk_capability_record_years_experience_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='professionalreview',
            constraint=models.CheckConstraint(condition=models.Q(('system_recommendation', ''), ('system_confidence__isnull', False), _connector='OR'), name='chk_professional_review_system_confidence_required'),
        ),
        migrations.AddConstraint(
            model_name='professionalreview',
            constraint=models.CheckConstraint(condition=models.Q(('system_recommendation', ''), models.Q(('ruleset_version', ''), _negated=True), _connector='OR'), name='chk_professional_review_ruleset_version_required'),
        ),
        migrations.AddConstraint(
            model_name='professionalreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'APPROVED'), _negated=True), models.Q(('final_classification', ''), _negated=True), _connector='OR'), name='chk_professional_review_final_classification_required'),
        ),
        migrations.AddConstraint(
            model_name='professionalreview',
            constraint=models.CheckConstraint(condition=models.Q(('decision', 'PENDING'), ('decided_at__isnull', False), _connector='OR'), name='chk_professional_review_decided_at_required'),
        ),
    ]
