# Generated by Django 5.2.11 on 2026-08-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_alter_professionalprofile_profile_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capabilityrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'CapabilityRecord', 'verbose_name_plural': 'CapabilityRecord'},
        ),
        migrations.AlterModelOptions(
            name='contactrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'ContactRecord', 'verbose_name_plural': 'ContactRecord'},
        ),
        migrations.AlterModelOptions(
            name='credentialrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'CredentialRecord', 'verbose_name_plural': 'CredentialRecord'},
        ),
        migrations.AlterModelOptions(
            name='professionalprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'ProfessionalProfile', 'verbose_name_plural': 'ProfessionalProfile'},
        ),
        migrations.AlterModelOptions(
            name='professionalreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'ProfessionalReview', 'verbose_name_plural': 'ProfessionalReview'},
        ),
    ]
