"""Hand-written migration — not generated by makemigrations.

Same root cause as catalog/migrations/0002_fix_option_set_fk_drift.py:
professionals/migrations/0001_initial.py was edited in place after already
being applied to some databases, so `migrate` (which only tracks migrations
as applied/unapplied by name) and `makemigrations` (which diffs models
against the *current* migration file content) both see nothing to do, even
though the live table predates the edit.

Affects CredentialRecord (missing issuing_organization_other,
primary_evidence, related_industry; client_organization drifted from an
auto-named FK column to an explicit db_column) and ContactRecord (missing
organization_other). CredentialRecordItem's table is missing outright —
that model was added after this drift point entirely.

Only rebuilds a table when it's both drifted AND empty — rebuilding is safe
with nothing in it to lose. A drifted table that already has rows is left
alone with an explicit error, since reconciling real data automatically
isn't safe to guess at here.
"""

from django.db import migrations


def _columns(cursor, table):
    cursor.execute(f"PRAGMA table_info({table})")
    return {row[1] for row in cursor.fetchall()}


def _row_count(cursor, table):
    cursor.execute(f"SELECT COUNT(*) FROM {table}")
    return cursor.fetchone()[0]


def fix_drift(apps, schema_editor):
    CredentialRecord = apps.get_model("professionals", "CredentialRecord")
    ContactRecord = apps.get_model("professionals", "ContactRecord")
    CredentialRecordItem = apps.get_model("professionals", "CredentialRecordItem")

    with schema_editor.connection.cursor() as cursor:
        for model in (CredentialRecord, ContactRecord):
            table = model._meta.db_table
            expected = {f.column for f in model._meta.get_fields() if hasattr(f, "column")}
            actual = _columns(cursor, table)
            if not (expected - actual):
                continue
            if _row_count(cursor, table) != 0:
                raise RuntimeError(
                    f"{table} has drifted from the current model shape and "
                    "already has rows — rebuilding it automatically would "
                    "lose data. Reconcile it by hand before migrating."
                )
            cursor.execute(f'DROP TABLE "{table}"')
            schema_editor.create_model(model)

        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name=%s",
            [CredentialRecordItem._meta.db_table],
        )
        if cursor.fetchone() is None:
            schema_editor.create_model(CredentialRecordItem)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0002_alter_professionalprofile_profile_status"),
    ]

    operations = [
        migrations.RunPython(fix_drift, noop_reverse),
    ]
