# Generated by Django 5.2.11 on 2026-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_alter_capabilityrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='industries_served',
            field=models.JSONField(blank=True, default=list, help_text='Derived list of ReferenceValue codes (option_set=INDUSTRY) from all VERIFIED ProfessionalScope rows; system-managed.'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='total_career_experience_months',
            field=models.PositiveIntegerField(default=0, help_text='Union-merged calendar experience across all EmploymentRecord / ProjectRecord rows, person-wide; never manually edited.'),
        ),
        migrations.AlterField(
            model_name='credentialrecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expiring soon'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('PENDING_VERIFICATION', 'Pending verification'), ('REVOKED', 'Revoked'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', help_text='Current credential lifecycle status.', max_length=20),
        ),
    ]
