# Generated by Django 5.2.11 on 2026-09-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_add_calculated_experience_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='current_classification',
        ),
    ]
