# Generated by Django 5.2.11 on 2026-08-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_professionalprofile_industries_served_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='current_classification',
            field=models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('CANDIDATE', 'Candidate'), ('MENTOR', 'Mentor'), ('BOTH', 'Both')], default='UNCLASSIFIED', help_text='Current professional classification.', max_length=20),
        ),
        migrations.AlterField(
            model_name='professionalreview',
            name='previous_classification',
            field=models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('CANDIDATE', 'Candidate'), ('MENTOR', 'Mentor'), ('BOTH', 'Both')], help_text='Classification before review.', max_length=20),
        ),
        migrations.AlterField(
            model_name='professionalreview',
            name='proposed_classification',
            field=models.CharField(blank=True, choices=[('CANDIDATE', 'Candidate'), ('MENTOR', 'Mentor'), ('BOTH', 'Both')], help_text='Proposed classification.', max_length=20),
        ),
        migrations.AlterField(
            model_name='professionalreview',
            name='system_recommendation',
            field=models.CharField(blank=True, choices=[('CANDIDATE', 'Candidate'), ('MENTOR', 'Mentor'), ('BOTH', 'Both'), ('INSUFFICIENT_DATA', 'Insufficient data')], help_text='Classification suggested by system rules.', max_length=20),
        ),
    ]
