# Generated by Django 5.2.11 on 2026-08-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_alter_professionalprofile_current_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrecord',
            name='data_classification',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PROFESSIONAL', 'Professional'), ('SENSITIVE_PII', 'Sensitive PII'), ('RESTRICTED_PII', 'Restricted PII'), ('COMMERCIAL', 'Commercial'), ('HEALTH', 'Health')], help_text='Privacy classification. Reference=SENSITIVE_PII; emergency=RESTRICTED_PII — set explicitly per contact_type.', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='resume_visibility',
            field=models.CharField(choices=[('NEVER', 'Never'), ('ALWAYS', 'Always'), ('OPTIONAL', 'Optional'), ('CLIENT_SPECIFIC', 'Client specific')], help_text='Resume inclusion rule. Reference default=CLIENT_SPECIFIC; emergency=NEVER — set explicitly per contact_type.', max_length=30),
        ),
    ]
