# Generated by Django 5.2.11 on 2026-08-03 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role_snapshot', models.CharField(blank=True, help_text='Role/permission context of actor captured at event time.', max_length=80)),
                ('action', models.CharField(help_text='Action performed; controlled action codes such as CREATE_TENANT, APPROVE_USER, VERIFY, CLASSIFY, ASSESS, GENERATE_RESUME.', max_length=80)),
                ('object_id', models.PositiveBigIntegerField(help_text='Target row identifier.')),
                ('before_data', models.JSONField(blank=True, help_text='State before change; sensitive values masked; size-limited.', null=True)),
                ('after_data', models.JSONField(blank=True, help_text='State after change; sensitive values masked; size-limited.', null=True)),
                ('reason', models.TextField(blank=True, help_text='Business reason; required for override, rejection, suspension and revocation actions.', max_length=3000)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Workflow correlation identifier; shared by events in one transaction/workflow.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Request IP address.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Sanitised and length-limited request client information.', max_length=1000)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Event timestamp; append-only.')),
                ('actor', models.ForeignKey(blank=True, help_text='User performing action; NULL for system tasks; same tenant unless platform action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.usertbl')),
                ('content_type', models.ForeignKey(help_text='Target model; restricted allow-list.', on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant context; NULL only for platform-level action.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'db_table': 'governance_audit_event',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
