"""
Hand-written migration — not generated by makemigrations.

Fixes schema drift caused by governance/migrations/0001_initial.py having
been rewritten (to add CreateModel operations for CalculationRuleSet,
CalculationRule, CalculatedFieldOverride and CalculatedFieldValueHistory)
after it was already marked applied on some databases. On those databases
only AuditEvent actually got created; the other four tables were never
created because their CreateModel calls did not exist yet at the time
0001_initial last ran there.

This migration runs between 0001_initial and 0002_initial (see the
dependency added to 0002_initial) and:

1. Creates whichever of the four governance tables are missing, using the
   historical model state as of right after 0001_initial. This intentionally
   does NOT include the FK fields/indexes/constraints that 0002_initial adds
   afterwards (tenant, created_by, etc.) — those are added by 0002_initial's
   own AddField/AddIndex/AddConstraint operations, exactly as they would be
   on a database where 0001_initial and 0002_initial ran in their original,
   intended order.

2. Drops audit_event.tenant_id if it already exists. Some databases have an
   AuditEvent table pre-dating the rewritten 0001_initial that already has a
   tenant_id column (from a since-removed migration). 0002_initial's first
   operation unconditionally re-adds that same column via AddField, which
   fails with "duplicate column name" on such a database. Dropping it here
   (only ever seen empty in practice) lets 0002_initial re-add it cleanly.

Idempotent: a database that already matches the current schema is a no-op.
"""

from django.db import migrations


def fix_drift(apps, schema_editor):
    connection = schema_editor.connection

    def table_exists(table_name):
        return table_name in connection.introspection.table_names()

    def get_columns(table_name):
        if not table_exists(table_name):
            return set()
        with connection.cursor() as cursor:
            description = connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        return {column.name for column in description}

    # ------------------------------------------------------------------
    # 1. Create missing governance tables (pre-0002_initial state)
    # ------------------------------------------------------------------

    model_names = (
        "CalculationRuleSet",
        "CalculationRule",
        "CalculatedFieldOverride",
        "CalculatedFieldValueHistory",
    )

    missing = [
        apps.get_model("governance", name)
        for name in model_names
        if not table_exists(apps.get_model("governance", name)._meta.db_table)
    ]

    progress = True
    while missing and progress:
        progress = False
        still_missing = []

        for model in missing:
            try:
                schema_editor.create_model(model)
                progress = True
            except Exception:
                # Usually a FK dependency whose table isn't created yet.
                still_missing.append(model)

        missing = still_missing

    if missing:
        raise RuntimeError(
            "Could not create governance tables after resolving FK "
            "dependencies: "
            + ", ".join(model._meta.db_table for model in missing)
        )

    # ------------------------------------------------------------------
    # 2. AuditEvent: drop a pre-existing tenant_id so 0002_initial's
    #    AddField can add it cleanly.
    # ------------------------------------------------------------------

    AuditEvent = apps.get_model("governance", "AuditEvent")
    audit_table = AuditEvent._meta.db_table
    audit_columns = get_columns(audit_table)

    if "tenant_id" in audit_columns:
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT name FROM sqlite_master "
                "WHERE type='index' AND tbl_name=%s AND sql LIKE '%%tenant_id%%'",
                [audit_table],
            )
            index_names = [row[0] for row in cursor.fetchall()]
            for index_name in index_names:
                cursor.execute(f"DROP INDEX {index_name}")

            cursor.execute(f"ALTER TABLE {audit_table} DROP COLUMN tenant_id")


def noop_reverse(apps, schema_editor):
    """
    This is a data-preserving drift repair; intentionally not reversed.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            fix_drift,
            noop_reverse,
        ),
    ]
