# Generated by Django 5.2.11 on 2026-08-26 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedFieldOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Safe external identifier used in APIs and integrations.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_id', models.PositiveBigIntegerField(help_text='Target row identifier.')),
                ('field_name', models.CharField(help_text="Exact field name on the target model holding the current deciding value, e.g. 'current_qualion_level', 'is_deployable', 'headline'.", max_length=80)),
                ('calculation_field_code', models.CharField(choices=[('CALENDAR_EXPERIENCE', 'Calendar experience'), ('VERIFIED_FIELD_DAYS', 'Verified field days'), ('VERIFIED_PROJECT_COUNT', 'Verified project count'), ('HIGHEST_AUTHORITY_REACHED', 'Highest authority reached'), ('QUALION_LEVEL', 'Qualion level (L0-L5)'), ('PROFESSIONAL_HEADLINE', 'Professional headline'), ('PROFESSIONAL_SUMMARY', 'Professional summary'), ('PRIMARY_ROLE', 'Primary role'), ('ADDITIONAL_ROLES', 'Additional roles'), ('INDUSTRIES_SERVED', 'Industries served'), ('PROJECT_RESPONSIBILITY_BULLETS', 'Project responsibility bullets'), ('TOTAL_CAREER_EXPERIENCE', 'Total career experience'), ('DEPLOYABILITY_FLAG', 'Deployability flag'), ('CREDENTIAL_STATUS', 'Credential status'), ('CANDIDATE_MENTOR_CLASSIFICATION', 'Candidate/Mentor classification')], db_index=True, help_text='Which of the 15 system-calculated fields this is, independent of the target model/field_name.', max_length=40)),
                ('request_type', models.CharField(choices=[('CORRECTION', 'Correction'), ('EXCEPTIONAL_OVERRIDE', 'Exceptional override')], help_text="Correction (source data was wrong) or Exceptional Override (source data is right, rule doesn't fit).", max_length=30)),
                ('system_calculated_value', models.JSONField(help_text='Original system output at the time of the request. Immutable snapshot; never overwritten even after approval.')),
                ('system_calculated_at', models.DateTimeField(help_text='When the system produced system_calculated_value.')),
                ('system_ruleset_version', models.CharField(blank=True, help_text='Calculation ruleset/version used.', max_length=30)),
                ('proposed_value', models.JSONField(help_text='Value the requester/reviewer is proposing instead.')),
                ('override_reason_code', models.CharField(choices=[('SOURCE_DATA_INCORRECT', 'Source data incorrect'), ('SOURCE_DATA_INCOMPLETE', 'Source data incomplete'), ('RULE_DOES_NOT_FIT_SITUATION', 'Automated rule does not represent the professional situation'), ('EVIDENCE_RECEIVED_LATE', 'Additional evidence received after calculation'), ('SYSTEM_DEFECT', 'System/calculation defect'), ('OTHER', 'Other (see rationale)')], help_text='Controlled reason category for the proposed change.', max_length=40)),
                ('rationale', models.TextField(help_text='Detailed justification for the proposed value. Always required.', max_length=3000)),
                ('requested_at', models.DateTimeField(help_text='Request submission timestamp.')),
                ('review_notes', models.TextField(blank=True, help_text="Reviewer's assessment notes.", max_length=3000)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Required once decision leaves PENDING.', null=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('RECOMMENDED', 'Recommended'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', help_text='Current workflow state of this override request.', max_length=20)),
                ('final_approved_value', models.JSONField(blank=True, help_text='Value confirmed by the approver; required when decision=APPROVED. This becomes the new current deciding value on the target field and is also written to CalculatedFieldValueHistory.', null=True)),
                ('decision_reason', models.TextField(blank=True, help_text='Required for REJECTED; recommended for all non-PENDING decisions.', max_length=3000)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Required when decision is APPROVED or REJECTED.', null=True)),
                ('four_eyes_required', models.BooleanField(default=False, help_text='Set true for L4/L5 and other high-impact outcomes per QUALION_QP-10; reviewed_by and approved_by must then be different authorised individuals.')),
                ('effective_from', models.DateField(blank=True, help_text='Date the final_approved_value takes effect.', null=True)),
                ('review_due_date', models.DateField(blank=True, help_text='Optional re-review/expiry date, mainly for time-bound EXCEPTIONAL_OVERRIDE decisions.', null=True)),
            ],
            options={
                'verbose_name': 'CalculatedFieldOverride',
                'verbose_name_plural': 'CalculatedFieldOverride',
                'db_table': 'governance_calculated_field_override',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculatedFieldValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_id', models.PositiveBigIntegerField(help_text='Target row identifier.')),
                ('field_name', models.CharField(help_text='Exact field name on the target model.', max_length=80)),
                ('calculation_field_code', models.CharField(choices=[('CALENDAR_EXPERIENCE', 'Calendar experience'), ('VERIFIED_FIELD_DAYS', 'Verified field days'), ('VERIFIED_PROJECT_COUNT', 'Verified project count'), ('HIGHEST_AUTHORITY_REACHED', 'Highest authority reached'), ('QUALION_LEVEL', 'Qualion level (L0-L5)'), ('PROFESSIONAL_HEADLINE', 'Professional headline'), ('PROFESSIONAL_SUMMARY', 'Professional summary'), ('PRIMARY_ROLE', 'Primary role'), ('ADDITIONAL_ROLES', 'Additional roles'), ('INDUSTRIES_SERVED', 'Industries served'), ('PROJECT_RESPONSIBILITY_BULLETS', 'Project responsibility bullets'), ('TOTAL_CAREER_EXPERIENCE', 'Total career experience'), ('DEPLOYABILITY_FLAG', 'Deployability flag'), ('CREDENTIAL_STATUS', 'Credential status'), ('CANDIDATE_MENTOR_CLASSIFICATION', 'Candidate/Mentor classification')], db_index=True, help_text='Which of the 15 system-calculated fields this change belongs to.', max_length=40)),
                ('previous_value', models.JSONField(blank=True, help_text='Value immediately before this change; NULL for the first record.', null=True)),
                ('new_value', models.JSONField(help_text='Value immediately after this change (the new current value).')),
                ('change_source', models.CharField(choices=[('SYSTEM_RECALCULATION', 'System recalculation'), ('CORRECTION_RECALCULATION', 'Recalculated after source-record correction'), ('OVERRIDE_APPROVED', 'Exceptional override approved')], db_index=True, help_text='Why the value changed.', max_length=30)),
                ('effective_from', models.DateField(blank=True, help_text='Date the new_value takes/took effect.', null=True)),
                ('recalculation_ruleset_version', models.CharField(blank=True, help_text='Ruleset/version used, for SYSTEM_RECALCULATION/CORRECTION_RECALCULATION rows.', max_length=30)),
            ],
            options={
                'verbose_name': 'CalculatedFieldValueHistory',
                'verbose_name_plural': 'CalculatedFieldValueHistory',
                'db_table': 'governance_calculated_field_value_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(help_text='Evaluation order within the rule set; lower runs first. First matching rule wins.')),
                ('label', models.CharField(help_text="Admin-facing description, e.g. 'Level 4 — Independent authority'.", max_length=160)),
                ('match_type', models.CharField(choices=[('ALL_CONDITIONS', 'All conditions must be met'), ('ANY_CONDITION', 'Any one condition is sufficient')], default='ALL_CONDITIONS', help_text='Whether every condition or any single condition triggers this rule.', max_length=20)),
                ('conditions', models.JSONField(help_text="Structured criteria evaluated against the professional's actual parameters for this field/scope, e.g. {'min_calendar_experience_months': 36, 'min_verified_field_days': 120, 'min_authority_status': 'PERFORMED', 'min_complexity_rating': 'INTERMEDIATE', 'required_certification_codes': ['NACE-CIP2']}. Schema validated by calculation_field_code, not enforced at the database level.")),
                ('concluded_value', models.JSONField(help_text="Value the system assigns when conditions are satisfied, e.g. {'qualion_level': 'L4'} or {'is_deployable': 'DEPLOYABLE_WITH_RESTRICTIONS'}.")),
                ('requires_four_eyes_approval', models.BooleanField(default=False, help_text='Overrides rule_set.default_requires_human_confirmation for this specific concluded value; set true for L4/L5 and other high-impact outcomes per QUALION_QP-10, requiring reviewer and approver to be different authorised individuals.')),
                ('is_active', models.BooleanField(default=True, help_text='Allows disabling a single rule without creating a new rule set version, only while the rule set itself is still DRAFT.')),
            ],
            options={
                'verbose_name': 'CalculationRule',
                'verbose_name_plural': 'CalculationRule',
                'db_table': 'governance_calculation_rule',
                'ordering': ['rule_set', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='CalculationRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Safe external identifier used in APIs and integrations.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_field_code', models.CharField(choices=[('CALENDAR_EXPERIENCE', 'Calendar experience'), ('VERIFIED_FIELD_DAYS', 'Verified field days'), ('VERIFIED_PROJECT_COUNT', 'Verified project count'), ('HIGHEST_AUTHORITY_REACHED', 'Highest authority reached'), ('QUALION_LEVEL', 'Qualion level (L0-L5)'), ('PROFESSIONAL_HEADLINE', 'Professional headline'), ('PROFESSIONAL_SUMMARY', 'Professional summary'), ('PRIMARY_ROLE', 'Primary role'), ('ADDITIONAL_ROLES', 'Additional roles'), ('INDUSTRIES_SERVED', 'Industries served'), ('PROJECT_RESPONSIBILITY_BULLETS', 'Project responsibility bullets'), ('TOTAL_CAREER_EXPERIENCE', 'Total career experience'), ('DEPLOYABILITY_FLAG', 'Deployability flag'), ('CREDENTIAL_STATUS', 'Credential status'), ('CANDIDATE_MENTOR_CLASSIFICATION', 'Candidate/Mentor classification')], db_index=True, help_text='Which of the 15 system-calculated fields this rule set derives.', max_length=40)),
                ('version', models.CharField(help_text="Rule set version label, e.g. '2026.1'.", max_length=30)),
                ('title', models.CharField(help_text='Short admin-facing name for this rule set.', max_length=180)),
                ('description', models.TextField(blank=True, help_text='Purpose and summary of this rule set.', max_length=2000)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', help_text='Publication status. Only PUBLISHED rule sets are used by the calculation engine.', max_length=20)),
                ('default_requires_human_confirmation', models.BooleanField(default=True, help_text='Whether concluded values from this rule set are treated as a System Recommendation requiring human confirmation before becoming a Final value (per QP-14), unless an individual rule overrides this with requires_four_eyes_approval/skip_confirmation.')),
                ('effective_from', models.DateField(blank=True, help_text='Date this rule set becomes effective once published.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Date this rule set stops being used, if scheduled for retirement.', null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Required when status=PUBLISHED.', null=True)),
                ('retired_at', models.DateTimeField(blank=True, help_text='Required when status=RETIRED.', null=True)),
            ],
            options={
                'verbose_name': 'CalculationRuleSet',
                'verbose_name_plural': 'CalculationRuleSet',
                'db_table': 'governance_calculation_rule_set',
                'ordering': ['calculation_field_code', 'scope', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role_snapshot', models.CharField(blank=True, help_text='Role/permission context of actor captured at event time.', max_length=80)),
                ('action', models.CharField(help_text='Action performed; controlled action codes such as CREATE_TENANT, APPROVE_USER, VERIFY, CLASSIFY, ASSESS, GENERATE_RESUME.', max_length=80)),
                ('object_id', models.PositiveBigIntegerField(help_text='Target row identifier.')),
                ('before_data', models.JSONField(blank=True, help_text='State before change; sensitive values masked; size-limited.', null=True)),
                ('after_data', models.JSONField(blank=True, help_text='State after change; sensitive values masked; size-limited.', null=True)),
                ('reason', models.TextField(blank=True, help_text='Business reason; required for override, rejection, suspension and revocation actions.', max_length=3000)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Workflow correlation identifier; shared by events in one transaction/workflow.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Request IP address.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Sanitised and length-limited request client information.', max_length=1000)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Event timestamp; append-only.')),
                ('actor', models.ForeignKey(blank=True, help_text='User performing action; NULL for system tasks; same tenant unless platform action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.usertbl')),
                ('content_type', models.ForeignKey(help_text='Target model; restricted allow-list.', on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'AuditEvent',
                'verbose_name_plural': 'AuditEvent',
                'db_table': 'governance_audit_event',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
