# Generated by Django 5.2.11 on 2026-08-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'AuditEvent', 'verbose_name_plural': 'AuditEvent'},
        ),
    ]
