# Generated by Django 5.2.11 on 2026-08-26 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('evidence', '0002_initial'),
        ('governance', '0001_initial'),
        ('governance', '0001_5_fix_schema_drift'),
        ('professionals', '0002_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant context; NULL only for platform-level action.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='calculatedfieldoverride',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Authorised Competency Decision-Maker/Validator; cannot equal requested_by; cannot equal the professional; separation of duties enforced at the service layer per role/permission, not merely administrative access.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides_approved', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='calculatedfieldoverride',
            name='content_type',
            field=models.ForeignKey(help_text='Target model holding the calculated field (e.g. competency.ProfessionalScope, professionals.ProfessionalProfile, professionals.CredentialRecord).', on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='calculatedfieldoverride',
            name='evidence',
            field=models.ForeignKey(blank=True, help_text='Supporting evidence/document reference. Required for EXCEPTIONAL_OVERRIDE; recommended for CORRECTION.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides', to='evidence.evidencedocument'),
        ),
        migrations.AddField(
            model_name='calculatedfieldoverride',
            name='professional',
            field=models.ForeignKey(help_text='Professional the calculated field belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='calculated_field_overrides', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='calculatedfieldoverride',
            name='requested_by',
            field=models.ForeignKey(help_text='User who raised the request; may be the professional themselves (request only, never self-approve) or a reviewer.', on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides_requested', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='calculatedfieldoverride',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Mentor/technical reviewer who assessed the request; cannot equal requested_by for reviewer-required fields; cannot equal the professional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides_reviewed', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='calculatedfieldoverride',
            name='supersedes',
            field=models.ForeignKey(blank=True, help_text='Prior override request for the same target+field that this one replaces or re-opens, preserving full request history.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='governance.calculatedfieldoverride'),
        ),
        migrations.AddField(
            model_name='calculatedfieldoverride',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='calculatedfieldvaluehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='NULL for system-triggered recalculations; set for override-driven changes (normally the approver).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_field_value_changes', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='calculatedfieldvaluehistory',
            name='content_type',
            field=models.ForeignKey(help_text='Target model holding the calculated field.', on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_value_history', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='calculatedfieldvaluehistory',
            name='override',
            field=models.ForeignKey(blank=True, help_text='Required when change_source=OVERRIDE_APPROVED; links the value change back to its full request/approval trail.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='value_history_entries', to='governance.calculatedfieldoverride'),
        ),
        migrations.AddField(
            model_name='calculatedfieldvaluehistory',
            name='professional',
            field=models.ForeignKey(help_text='Professional the calculated field belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='calculated_field_value_history', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='calculatedfieldvaluehistory',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='calculationruleset',
            name='created_by',
            field=models.ForeignKey(help_text='Tenant Admin/authorised author who created this rule set.', on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rule_sets_created', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='calculationruleset',
            name='published_by',
            field=models.ForeignKey(blank=True, help_text='User who published this version; required when PUBLISHED.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rule_sets_published', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='calculationruleset',
            name='scope',
            field=models.ForeignKey(blank=True, help_text='Industry/Scope this rule set applies to. NULL means tenant-wide default, used when no scope-specific PUBLISHED rule set exists. Required in practice for QUALION_LEVEL and HIGHEST_AUTHORITY_REACHED, which must not be evaluated globally.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rule_sets', to='catalog.scopecatalog'),
        ),
        migrations.AddField(
            model_name='calculationruleset',
            name='supersedes',
            field=models.ForeignKey(blank=True, help_text='Prior version of this tenant+field(+scope) rule set that this version replaces.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='governance.calculationruleset'),
        ),
        migrations.AddField(
            model_name='calculationruleset',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='rule_set',
            field=models.ForeignKey(help_text='Owning rule set. Must equal rule_set.tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='governance.calculationruleset'),
        ),
        migrations.AddIndex(
            model_name='calculatedfieldoverride',
            index=models.Index(fields=['content_type', 'object_id', 'field_name'], name='governance__content_0789c8_idx'),
        ),
        migrations.AddIndex(
            model_name='calculatedfieldoverride',
            index=models.Index(fields=['professional', 'calculation_field_code'], name='governance__profess_535d75_idx'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.CheckConstraint(condition=models.Q(('requested_by', models.F('approved_by')), _negated=True), name='chk_calc_override_requester_not_approver'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'APPROVED'), _negated=True), ('final_approved_value__isnull', False), _connector='OR'), name='chk_calc_override_final_value_required_on_approval'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'APPROVED'), _negated=True), ('approved_by__isnull', False), _connector='OR'), name='chk_calc_override_approver_required_on_approval'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'REJECTED'), _negated=True), models.Q(('decision_reason', ''), _negated=True), _connector='OR'), name='chk_calc_override_decision_reason_required_on_rejection'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision__in', ['APPROVED', 'REJECTED']), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='chk_calc_override_approved_at_required'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('request_type', 'EXCEPTIONAL_OVERRIDE'), _negated=True), ('evidence__isnull', False), _connector='OR'), name='chk_calc_override_evidence_required_for_exception'),
        ),
        migrations.AddIndex(
            model_name='calculatedfieldvaluehistory',
            index=models.Index(fields=['content_type', 'object_id', 'field_name', '-created_at'], name='governance__content_2c0373_idx'),
        ),
        migrations.AddIndex(
            model_name='calculatedfieldvaluehistory',
            index=models.Index(fields=['professional', 'calculation_field_code', '-created_at'], name='governance__profess_a18687_idx'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldvaluehistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('change_source', 'OVERRIDE_APPROVED'), _negated=True), ('override__isnull', False), _connector='OR'), name='chk_calc_value_history_override_required'),
        ),
        migrations.AddConstraint(
            model_name='calculationruleset',
            constraint=models.UniqueConstraint(fields=('tenant', 'calculation_field_code', 'scope', 'version'), name='uniq_calc_rule_set_tenant_field_scope_version'),
        ),
        migrations.AddConstraint(
            model_name='calculationruleset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PUBLISHED'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='chk_calc_rule_set_published_at_required'),
        ),
        migrations.AddConstraint(
            model_name='calculationruleset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PUBLISHED'), _negated=True), ('published_by__isnull', False), _connector='OR'), name='chk_calc_rule_set_published_by_required'),
        ),
        migrations.AddConstraint(
            model_name='calculationruleset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'RETIRED'), _negated=True), ('retired_at__isnull', False), _connector='OR'), name='chk_calc_rule_set_retired_at_required'),
        ),
        migrations.AddConstraint(
            model_name='calculationrule',
            constraint=models.UniqueConstraint(fields=('rule_set', 'sequence'), name='uniq_calc_rule_rule_set_sequence'),
        ),
    ]
