# Generated by Django 5.2.11 on 2026-09-10 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0003_alter_formfield_data_type'),
        ('governance', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationrule',
            options={'ordering': ['calculation_field_code', 'sequence'], 'verbose_name': 'CalculationRule', 'verbose_name_plural': 'CalculationRule'},
        ),
        migrations.RemoveConstraint(
            model_name='calculationrule',
            name='uniq_calc_rule_rule_set_sequence',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='concluded_value',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='rule_set',
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='block_if_pending_rejection',
            field=models.BooleanField(default=False, help_text='If true, this rule does not match while the professional has an unresolved REJECTED ProfessionalReview of type RECLASSIFICATION. CANDIDATE_MENTOR_CLASSIFICATION rules only.'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='calculation_field_code',
            field=models.CharField(blank=True, choices=[('QUALION_LEVEL', 'QUALION_LEVEL'), ('DEPLOYABILITY_FLAG', 'DEPLOYABILITY_FLAG'), ('CANDIDATE_MENTOR_CLASSIFICATION', 'CANDIDATE_MENTOR_CLASSIFICATION')], db_index=True, help_text='Which system-calculated field this rule belongs to. Only QUALION_LEVEL, DEPLOYABILITY_FLAG and CANDIDATE_MENTOR_CLASSIFICATION are valid here — the other 12 fields are fixed formulas and never have a CalculationRule; enforced in clean().', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='concluded_classification',
            field=models.CharField(blank=True, choices=[('CANDIDATE', 'Candidate'), ('MENTOR', 'Mentor'), ('BOTH', 'Both'), ('UNCLASSIFIED', 'Unclassified')], help_text='Value assigned when this rule matches. CANDIDATE_MENTOR_CLASSIFICATION rules only.', max_length=20),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='concluded_deployability_status',
            field=models.CharField(blank=True, choices=[('DEPLOYABLE', 'Deployable'), ('DEPLOYABLE_WITH_RESTRICTIONS', 'Deployable with restrictions'), ('REVIEW_REQUIRED', 'Review required'), ('NOT_DEPLOYABLE', 'Not deployable')], help_text='Value assigned when this rule matches. DEPLOYABILITY_FLAG rules only.', max_length=30),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='concluded_qualion_level',
            field=models.ForeignKey(blank=True, help_text='Value assigned when this rule matches. QUALION_LEVEL rules only (option_set QUALION_LEVEL).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calc_rules_concluded_qualion_level', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Tenant Admin/authorised author who created this rule.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rules_created', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='max_calendar_experience_months',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum ProfessionalScope.calendar_experience_months for this scope.', null=True),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='max_days_to_credential_expiry',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Only meaningful when required_credential_types is set: the matching credential must expire within this many days (e.g. 30) — used for 'expiring soon' deployability rules. Leave blank to not check expiry at all.", null=True),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='max_qualion_level',
            field=models.ForeignKey(blank=True, help_text='Maximum current_qualion_level rank required, ranked by ReferenceValue.sort_order (option_set QUALION_LEVEL). Used by DEPLOYABILITY_FLAG/CANDIDATE_MENTOR_CLASSIFICATION rules — not QUALION_LEVEL rules themselves, which would be circular.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calc_rules_max_qualion_level', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='max_verified_field_days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum ProfessionalScope.verified_field_days for this scope.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='max_verified_project_count',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum ProfessionalScope.verified_project_count (approved/verified projects) for this scope.', null=True),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='min_authority_status',
            field=models.ForeignKey(blank=True, help_text='Minimum current_authority_status rank required, ranked by sort_order (option_set AUTHORITY_STATUS).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calc_rules_min_authority_status', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='min_calendar_experience_months',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum ProfessionalScope.calendar_experience_months for this scope.', null=True),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='min_complexity_rating',
            field=models.ForeignKey(blank=True, help_text='Minimum complexity_rating rank required, ranked by sort_order (option_set COMPLEXITY).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calc_rules_min_complexity_rating', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='min_ethics_independence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum latest CompetencyAssessment.ethics_independence_score (0.00-100.00). CANDIDATE_MENTOR_CLASSIFICATION rules only.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='min_qualion_level',
            field=models.ForeignKey(blank=True, help_text='Minimum current_qualion_level rank required, ranked by ReferenceValue.sort_order (option_set QUALION_LEVEL). Used by DEPLOYABILITY_FLAG/CANDIDATE_MENTOR_CLASSIFICATION rules — not QUALION_LEVEL rules themselves, which would be circular.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calc_rules_min_qualion_level', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='min_verified_field_days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum ProfessionalScope.verified_field_days for this scope.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='min_verified_project_count',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum ProfessionalScope.verified_project_count (approved/verified projects) for this scope.', null=True),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='require_active_credential',
            field=models.BooleanField(default=False, help_text='Only meaningful when required_credential_types is set: whether the matching credential must currently be status=ACTIVE, vs. any status.'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='require_latest_assessment_decision',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], help_text='The latest CompetencyAssessment for this professional+scope must have this decision (e.g. APPROVED) for the rule to match. Blank = not checked.', max_length=20),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='required_credential_types',
            field=models.ManyToManyField(blank=True, help_text='Professional must hold a CredentialRecord of at least one of these types (option_set CREDENTIAL_TYPE) for this scope. Empty = no credential required by this rule.', related_name='calc_rules_requiring_credential', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='scope',
            field=models.ManyToManyField(blank=True, help_text="Industry/Scopes this rule applies to. An empty selection means tenant-wide (e.g. CANDIDATE_MENTOR_CLASSIFICATION is typically evaluated across a professional's best scope, not one specific scope). At least one scope is expected for QUALION_LEVEL and DEPLOYABILITY_FLAG.", related_name='calculation_rules', to='catalog.scopecatalog'),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable a single rule without deleting it. Takes effect immediately — there is no DRAFT/PUBLISHED staging here.'),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='match_type',
            field=models.CharField(choices=[('ALL_CONDITIONS', 'All conditions must be met'), ('ANY_CONDITION', 'Any one condition is sufficient')], default='ALL_CONDITIONS', help_text='Whether every populated condition, or any single one, triggers this rule.', max_length=20),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='requires_four_eyes_approval',
            field=models.BooleanField(default=False, help_text='Set true for L4/L5 and other high-impact outcomes per QUALION_QP-10, requiring reviewer and approver to be different authorised individuals.'),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='sequence',
            field=models.PositiveSmallIntegerField(help_text='Evaluation order within this tenant+field+scope ladder; lower runs first. First matching rule wins.'),
        ),
    ]
