# Generated by Django 5.2.11 on 2026-08-24 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_consentrecord_options_and_more'),
        ('catalog', '0002_alter_formfield_options_alter_formmodule_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('evidence', '0003_alter_evidencedocument_options'),
        ('governance', '0002_alter_auditevent_options'),
        ('professionals', '0003_alter_capabilityrecord_options_and_more'),
        ('tenancy', '0002_module_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedFieldOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Safe external identifier used in APIs and integrations.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_id', models.PositiveBigIntegerField(help_text='Target row identifier.')),
                ('field_name', models.CharField(help_text="Exact field name on the target model holding the current deciding value, e.g. 'current_qualion_level', 'is_deployable', 'headline'.", max_length=80)),
                ('calculation_field_code', models.CharField(choices=[('CALENDAR_EXPERIENCE', 'Calendar experience'), ('VERIFIED_FIELD_DAYS', 'Verified field days'), ('VERIFIED_PROJECT_COUNT', 'Verified project count'), ('HIGHEST_AUTHORITY_REACHED', 'Highest authority reached'), ('QUALION_LEVEL', 'Qualion level (L0-L5)'), ('PROFESSIONAL_HEADLINE', 'Professional headline'), ('PROFESSIONAL_SUMMARY', 'Professional summary'), ('PRIMARY_ROLE', 'Primary role'), ('ADDITIONAL_ROLES', 'Additional roles'), ('INDUSTRIES_SERVED', 'Industries served'), ('PROJECT_RESPONSIBILITY_BULLETS', 'Project responsibility bullets'), ('TOTAL_CAREER_EXPERIENCE', 'Total career experience'), ('DEPLOYABILITY_FLAG', 'Deployability flag'), ('CREDENTIAL_STATUS', 'Credential status'), ('CANDIDATE_MENTOR_CLASSIFICATION', 'Candidate/Mentor classification')], db_index=True, help_text='Which of the 15 system-calculated fields this is, independent of the target model/field_name.', max_length=40)),
                ('request_type', models.CharField(choices=[('CORRECTION', 'Correction'), ('EXCEPTIONAL_OVERRIDE', 'Exceptional override')], help_text="Correction (source data was wrong) or Exceptional Override (source data is right, rule doesn't fit).", max_length=30)),
                ('system_calculated_value', models.JSONField(help_text='Original system output at the time of the request. Immutable snapshot; never overwritten even after approval.')),
                ('system_calculated_at', models.DateTimeField(help_text='When the system produced system_calculated_value.')),
                ('system_ruleset_version', models.CharField(blank=True, help_text='Calculation ruleset/version used.', max_length=30)),
                ('proposed_value', models.JSONField(help_text='Value the requester/reviewer is proposing instead.')),
                ('override_reason_code', models.CharField(choices=[('SOURCE_DATA_INCORRECT', 'Source data incorrect'), ('SOURCE_DATA_INCOMPLETE', 'Source data incomplete'), ('RULE_DOES_NOT_FIT_SITUATION', 'Automated rule does not represent the professional situation'), ('EVIDENCE_RECEIVED_LATE', 'Additional evidence received after calculation'), ('SYSTEM_DEFECT', 'System/calculation defect'), ('OTHER', 'Other (see rationale)')], help_text='Controlled reason category for the proposed change.', max_length=40)),
                ('rationale', models.TextField(help_text='Detailed justification for the proposed value. Always required.', max_length=3000)),
                ('requested_at', models.DateTimeField(help_text='Request submission timestamp.')),
                ('review_notes', models.TextField(blank=True, help_text="Reviewer's assessment notes.", max_length=3000)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Required once decision leaves PENDING.', null=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('RECOMMENDED', 'Recommended'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', help_text='Current workflow state of this override request.', max_length=20)),
                ('final_approved_value', models.JSONField(blank=True, help_text='Value confirmed by the approver; required when decision=APPROVED. This becomes the new current deciding value on the target field and is also written to CalculatedFieldValueHistory.', null=True)),
                ('decision_reason', models.TextField(blank=True, help_text='Required for REJECTED; recommended for all non-PENDING decisions.', max_length=3000)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Required when decision is APPROVED or REJECTED.', null=True)),
                ('four_eyes_required', models.BooleanField(default=False, help_text='Set true for L4/L5 and other high-impact outcomes per QUALION_QP-10; reviewed_by and approved_by must then be different authorised individuals.')),
                ('effective_from', models.DateField(blank=True, help_text='Date the final_approved_value takes effect.', null=True)),
                ('review_due_date', models.DateField(blank=True, help_text='Optional re-review/expiry date, mainly for time-bound EXCEPTIONAL_OVERRIDE decisions.', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Authorised Competency Decision-Maker/Validator; cannot equal requested_by; cannot equal the professional; separation of duties enforced at the service layer per role/permission, not merely administrative access.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides_approved', to='accounts.usertbl')),
                ('content_type', models.ForeignKey(help_text='Target model holding the calculated field (e.g. competency.ProfessionalScope, professionals.ProfessionalProfile, professionals.CredentialRecord).', on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides', to='contenttypes.contenttype')),
                ('evidence', models.ForeignKey(blank=True, help_text='Supporting evidence/document reference. Required for EXCEPTIONAL_OVERRIDE; recommended for CORRECTION.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides', to='evidence.evidencedocument')),
                ('professional', models.ForeignKey(help_text='Professional the calculated field belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='calculated_field_overrides', to='professionals.professionalprofile')),
                ('requested_by', models.ForeignKey(help_text='User who raised the request; may be the professional themselves (request only, never self-approve) or a reviewer.', on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides_requested', to='accounts.usertbl')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Mentor/technical reviewer who assessed the request; cannot equal requested_by for reviewer-required fields; cannot equal the professional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides_reviewed', to='accounts.usertbl')),
                ('supersedes', models.ForeignKey(blank=True, help_text='Prior override request for the same target+field that this one replaces or re-opens, preserving full request history.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='governance.calculatedfieldoverride')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'CalculatedFieldOverride',
                'verbose_name_plural': 'CalculatedFieldOverride',
                'db_table': 'governance_calculated_field_override',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculatedFieldValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_id', models.PositiveBigIntegerField(help_text='Target row identifier.')),
                ('field_name', models.CharField(help_text='Exact field name on the target model.', max_length=80)),
                ('calculation_field_code', models.CharField(choices=[('CALENDAR_EXPERIENCE', 'Calendar experience'), ('VERIFIED_FIELD_DAYS', 'Verified field days'), ('VERIFIED_PROJECT_COUNT', 'Verified project count'), ('HIGHEST_AUTHORITY_REACHED', 'Highest authority reached'), ('QUALION_LEVEL', 'Qualion level (L0-L5)'), ('PROFESSIONAL_HEADLINE', 'Professional headline'), ('PROFESSIONAL_SUMMARY', 'Professional summary'), ('PRIMARY_ROLE', 'Primary role'), ('ADDITIONAL_ROLES', 'Additional roles'), ('INDUSTRIES_SERVED', 'Industries served'), ('PROJECT_RESPONSIBILITY_BULLETS', 'Project responsibility bullets'), ('TOTAL_CAREER_EXPERIENCE', 'Total career experience'), ('DEPLOYABILITY_FLAG', 'Deployability flag'), ('CREDENTIAL_STATUS', 'Credential status'), ('CANDIDATE_MENTOR_CLASSIFICATION', 'Candidate/Mentor classification')], db_index=True, help_text='Which of the 15 system-calculated fields this change belongs to.', max_length=40)),
                ('previous_value', models.JSONField(blank=True, help_text='Value immediately before this change; NULL for the first record.', null=True)),
                ('new_value', models.JSONField(help_text='Value immediately after this change (the new current value).')),
                ('change_source', models.CharField(choices=[('SYSTEM_RECALCULATION', 'System recalculation'), ('CORRECTION_RECALCULATION', 'Recalculated after source-record correction'), ('OVERRIDE_APPROVED', 'Exceptional override approved')], db_index=True, help_text='Why the value changed.', max_length=30)),
                ('effective_from', models.DateField(blank=True, help_text='Date the new_value takes/took effect.', null=True)),
                ('recalculation_ruleset_version', models.CharField(blank=True, help_text='Ruleset/version used, for SYSTEM_RECALCULATION/CORRECTION_RECALCULATION rows.', max_length=30)),
                ('changed_by', models.ForeignKey(blank=True, help_text='NULL for system-triggered recalculations; set for override-driven changes (normally the approver).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_field_value_changes', to='accounts.usertbl')),
                ('content_type', models.ForeignKey(help_text='Target model holding the calculated field.', on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_value_history', to='contenttypes.contenttype')),
                ('override', models.ForeignKey(blank=True, help_text='Required when change_source=OVERRIDE_APPROVED; links the value change back to its full request/approval trail.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='value_history_entries', to='governance.calculatedfieldoverride')),
                ('professional', models.ForeignKey(help_text='Professional the calculated field belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='calculated_field_value_history', to='professionals.professionalprofile')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'CalculatedFieldValueHistory',
                'verbose_name_plural': 'CalculatedFieldValueHistory',
                'db_table': 'governance_calculated_field_value_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Safe external identifier used in APIs and integrations.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_field_code', models.CharField(choices=[('CALENDAR_EXPERIENCE', 'Calendar experience'), ('VERIFIED_FIELD_DAYS', 'Verified field days'), ('VERIFIED_PROJECT_COUNT', 'Verified project count'), ('HIGHEST_AUTHORITY_REACHED', 'Highest authority reached'), ('QUALION_LEVEL', 'Qualion level (L0-L5)'), ('PROFESSIONAL_HEADLINE', 'Professional headline'), ('PROFESSIONAL_SUMMARY', 'Professional summary'), ('PRIMARY_ROLE', 'Primary role'), ('ADDITIONAL_ROLES', 'Additional roles'), ('INDUSTRIES_SERVED', 'Industries served'), ('PROJECT_RESPONSIBILITY_BULLETS', 'Project responsibility bullets'), ('TOTAL_CAREER_EXPERIENCE', 'Total career experience'), ('DEPLOYABILITY_FLAG', 'Deployability flag'), ('CREDENTIAL_STATUS', 'Credential status'), ('CANDIDATE_MENTOR_CLASSIFICATION', 'Candidate/Mentor classification')], db_index=True, help_text='Which of the 15 system-calculated fields this rule set derives.', max_length=40)),
                ('version', models.CharField(help_text="Rule set version label, e.g. '2026.1'.", max_length=30)),
                ('title', models.CharField(help_text='Short admin-facing name for this rule set.', max_length=180)),
                ('description', models.TextField(blank=True, help_text='Purpose and summary of this rule set.', max_length=2000)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', help_text='Publication status. Only PUBLISHED rule sets are used by the calculation engine.', max_length=20)),
                ('default_requires_human_confirmation', models.BooleanField(default=True, help_text='Whether concluded values from this rule set are treated as a System Recommendation requiring human confirmation before becoming a Final value (per QP-14), unless an individual rule overrides this with requires_four_eyes_approval/skip_confirmation.')),
                ('effective_from', models.DateField(blank=True, help_text='Date this rule set becomes effective once published.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Date this rule set stops being used, if scheduled for retirement.', null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Required when status=PUBLISHED.', null=True)),
                ('retired_at', models.DateTimeField(blank=True, help_text='Required when status=RETIRED.', null=True)),
                ('created_by', models.ForeignKey(help_text='Tenant Admin/authorised author who created this rule set.', on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rule_sets_created', to='accounts.usertbl')),
                ('published_by', models.ForeignKey(blank=True, help_text='User who published this version; required when PUBLISHED.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rule_sets_published', to='accounts.usertbl')),
                ('scope', models.ForeignKey(blank=True, help_text='Industry/Scope this rule set applies to. NULL means tenant-wide default, used when no scope-specific PUBLISHED rule set exists. Required in practice for QUALION_LEVEL and HIGHEST_AUTHORITY_REACHED, which must not be evaluated globally.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rule_sets', to='catalog.scopecatalog')),
                ('supersedes', models.ForeignKey(blank=True, help_text='Prior version of this tenant+field(+scope) rule set that this version replaces.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='governance.calculationruleset')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'CalculationRuleSet',
                'verbose_name_plural': 'CalculationRuleSet',
                'db_table': 'governance_calculation_rule_set',
                'ordering': ['calculation_field_code', 'scope', '-version'],
            },
        ),
        migrations.CreateModel(
            name='CalculationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(help_text='Evaluation order within the rule set; lower runs first. First matching rule wins.')),
                ('label', models.CharField(help_text="Admin-facing description, e.g. 'Level 4 â€” Independent authority'.", max_length=160)),
                ('match_type', models.CharField(choices=[('ALL_CONDITIONS', 'All conditions must be met'), ('ANY_CONDITION', 'Any one condition is sufficient')], default='ALL_CONDITIONS', help_text='Whether every condition or any single condition triggers this rule.', max_length=20)),
                ('conditions', models.JSONField(help_text="Structured criteria evaluated against the professional's actual parameters for this field/scope, e.g. {'min_calendar_experience_months': 36, 'min_verified_field_days': 120, 'min_authority_status': 'PERFORMED', 'min_complexity_rating': 'INTERMEDIATE', 'required_certification_codes': ['NACE-CIP2']}. Schema validated by calculation_field_code, not enforced at the database level.")),
                ('concluded_value', models.JSONField(help_text="Value the system assigns when conditions are satisfied, e.g. {'qualion_level': 'L4'} or {'is_deployable': 'DEPLOYABLE_WITH_RESTRICTIONS'}.")),
                ('requires_four_eyes_approval', models.BooleanField(default=False, help_text='Overrides rule_set.default_requires_human_confirmation for this specific concluded value; set true for L4/L5 and other high-impact outcomes per QUALION_QP-10, requiring reviewer and approver to be different authorised individuals.')),
                ('is_active', models.BooleanField(default=True, help_text='Allows disabling a single rule without creating a new rule set version, only while the rule set itself is still DRAFT.')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('rule_set', models.ForeignKey(help_text='Owning rule set. Must equal rule_set.tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='governance.calculationruleset')),
            ],
            options={
                'verbose_name': 'CalculationRule',
                'verbose_name_plural': 'CalculationRule',
                'db_table': 'governance_calculation_rule',
                'ordering': ['rule_set', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='calculatedfieldoverride',
            index=models.Index(fields=['content_type', 'object_id', 'field_name'], name='governance__content_0789c8_idx'),
        ),
        migrations.AddIndex(
            model_name='calculatedfieldoverride',
            index=models.Index(fields=['professional', 'calculation_field_code'], name='governance__profess_535d75_idx'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.CheckConstraint(check=models.Q(('requested_by', models.F('approved_by')), _negated=True), name='chk_calc_override_requester_not_approver'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('decision', 'APPROVED'), _negated=True), ('final_approved_value__isnull', False), _connector='OR'), name='chk_calc_override_final_value_required_on_approval'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('decision', 'APPROVED'), _negated=True), ('approved_by__isnull', False), _connector='OR'), name='chk_calc_override_approver_required_on_approval'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('decision', 'REJECTED'), _negated=True), models.Q(('decision_reason', ''), _negated=True), _connector='OR'), name='chk_calc_override_decision_reason_required_on_rejection'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('decision__in', ['APPROVED', 'REJECTED']), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='chk_calc_override_approved_at_required'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('request_type', 'EXCEPTIONAL_OVERRIDE'), _negated=True), ('evidence__isnull', False), _connector='OR'), name='chk_calc_override_evidence_required_for_exception'),
        ),
        migrations.AddIndex(
            model_name='calculatedfieldvaluehistory',
            index=models.Index(fields=['content_type', 'object_id', 'field_name', '-created_at'], name='governance__content_2c0373_idx'),
        ),
        migrations.AddIndex(
            model_name='calculatedfieldvaluehistory',
            index=models.Index(fields=['professional', 'calculation_field_code', '-created_at'], name='governance__profess_a18687_idx'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldvaluehistory',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('change_source', 'OVERRIDE_APPROVED'), _negated=True), ('override__isnull', False), _connector='OR'), name='chk_calc_value_history_override_required'),
        ),
        migrations.AddConstraint(
            model_name='calculationruleset',
            constraint=models.UniqueConstraint(fields=('tenant', 'calculation_field_code', 'scope', 'version'), name='uniq_calc_rule_set_tenant_field_scope_version'),
        ),
        migrations.AddConstraint(
            model_name='calculationruleset',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'PUBLISHED'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='chk_calc_rule_set_published_at_required'),
        ),
        migrations.AddConstraint(
            model_name='calculationruleset',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'PUBLISHED'), _negated=True), ('published_by__isnull', False), _connector='OR'), name='chk_calc_rule_set_published_by_required'),
        ),
        migrations.AddConstraint(
            model_name='calculationruleset',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'RETIRED'), _negated=True), ('retired_at__isnull', False), _connector='OR'), name='chk_calc_rule_set_retired_at_required'),
        ),
        migrations.AddConstraint(
            model_name='calculationrule',
            constraint=models.UniqueConstraint(fields=('rule_set', 'sequence'), name='uniq_calc_rule_rule_set_sequence'),
        ),
    ]
