# Generated by Django 5.2.11 on 2026-08-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_calculatedfieldoverride_calculatedfieldvaluehistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationrule',
            name='label',
            field=models.CharField(help_text="Admin-facing description, e.g. 'Level 4 — Independent authority'.", max_length=160),
        ),
    ]
