# Generated by Django 5.2.11 on 2026-09-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('competency', '0004_alter_competencyassessment_assessment_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('evidence', '0002_initial'),
        ('governance', '0003_alter_calculationrule_options_and_more'),
        ('professionals', '0004_add_calculated_experience_fields'),
        ('tenancy', '0003_alter_project_business_unit_alter_project_industry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculatedfieldoverride',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='calculatedfieldvaluehistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='calculatedfieldoverride',
            name='chk_calc_override_requester_not_approver',
        ),
        migrations.AddField(
            model_name='calculatedfieldoverride',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups all field overrides created from the same admin submit.', null=True),
        ),
        migrations.AddField(
            model_name='calculatedfieldoverride',
            name='professional_scope',
            field=models.ForeignKey(blank=True, help_text='Set only for ProfessionalScope-based calculated fields.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides', to='competency.professionalscope'),
        ),
        migrations.AddField(
            model_name='calculatedfieldvaluehistory',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='calculatedfieldvaluehistory',
            name='professional_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_value_history', to='competency.professionalscope'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides_approved', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='calculation_field_code',
            field=models.CharField(choices=[('CALENDAR_EXPERIENCE', 'Calendar experience'), ('VERIFIED_FIELD_DAYS', 'Verified field days'), ('VERIFIED_PROJECT_COUNT', 'Verified project count'), ('HIGHEST_AUTHORITY_REACHED', 'Highest authority reached'), ('QUALION_LEVEL', 'Qualion level (L0-L5)'), ('PROFESSIONAL_HEADLINE', 'Professional headline'), ('PROFESSIONAL_SUMMARY', 'Professional summary'), ('PRIMARY_ROLE', 'Primary role'), ('ADDITIONAL_ROLES', 'Additional roles'), ('INDUSTRIES_SERVED', 'Industries served'), ('PROJECT_RESPONSIBILITY_BULLETS', 'Project responsibility bullets'), ('TOTAL_CAREER_EXPERIENCE', 'Total career experience'), ('DEPLOYABILITY_FLAG', 'Deployability flag'), ('CREDENTIAL_STATUS', 'Credential status'), ('CANDIDATE_MENTOR_CLASSIFICATION', 'Candidate/Mentor classification')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='decision',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('RECOMMENDED', 'Recommended'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='decision_reason',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides', to='evidence.evidencedocument'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='field_name',
            field=models.CharField(help_text='Actual target field name. Multiple field names may be comma-separated for combined calculated fields.', max_length=100),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='final_approved_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='four_eyes_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='override_reason_code',
            field=models.CharField(choices=[('SOURCE_DATA_INCORRECT', 'Source data incorrect'), ('SOURCE_DATA_INCOMPLETE', 'Source data incomplete'), ('RULE_DOES_NOT_FIT_SITUATION', 'Automated rule does not represent the professional situation'), ('EVIDENCE_RECEIVED_LATE', 'Additional evidence received after calculation'), ('SYSTEM_DEFECT', 'System/calculation defect'), ('OTHER', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_field_overrides', to='professionals.professionalprofile'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='proposed_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='rationale',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='request_type',
            field=models.CharField(choices=[('CORRECTION', 'Correction'), ('EXCEPTIONAL_OVERRIDE', 'Exceptional override')], default='CORRECTION', max_length=30),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='requested_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides_requested', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='review_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='review_notes',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides_reviewed', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='governance.calculatedfieldoverride'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='system_calculated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='system_calculated_value',
            field=models.JSONField(blank=True, help_text='Value before the admin override was applied.', null=True),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='system_ruleset_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='calculation_field_code',
            field=models.CharField(choices=[('CALENDAR_EXPERIENCE', 'Calendar experience'), ('VERIFIED_FIELD_DAYS', 'Verified field days'), ('VERIFIED_PROJECT_COUNT', 'Verified project count'), ('HIGHEST_AUTHORITY_REACHED', 'Highest authority reached'), ('QUALION_LEVEL', 'Qualion level (L0-L5)'), ('PROFESSIONAL_HEADLINE', 'Professional headline'), ('PROFESSIONAL_SUMMARY', 'Professional summary'), ('PRIMARY_ROLE', 'Primary role'), ('ADDITIONAL_ROLES', 'Additional roles'), ('INDUSTRIES_SERVED', 'Industries served'), ('PROJECT_RESPONSIBILITY_BULLETS', 'Project responsibility bullets'), ('TOTAL_CAREER_EXPERIENCE', 'Total career experience'), ('DEPLOYABILITY_FLAG', 'Deployability flag'), ('CREDENTIAL_STATUS', 'Credential status'), ('CANDIDATE_MENTOR_CLASSIFICATION', 'Candidate/Mentor classification')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='change_source',
            field=models.CharField(choices=[('SYSTEM_RECALCULATION', 'System recalculation'), ('CORRECTION_RECALCULATION', 'Correction recalculation'), ('OVERRIDE_APPROVED', 'Override approved')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_field_value_changes', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_value_history', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='field_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='new_value',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='value_history_entries', to='governance.calculatedfieldoverride'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='previous_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_field_value_history', to='professionals.professionalprofile'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='recalculation_ruleset_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddIndex(
            model_name='calculatedfieldoverride',
            index=models.Index(fields=['batch_id'], name='governance__batch_i_4d10a4_idx'),
        ),
        migrations.AddIndex(
            model_name='calculatedfieldoverride',
            index=models.Index(fields=['professional_scope', 'calculation_field_code'], name='governance__profess_e2ab66_idx'),
        ),
        migrations.AddIndex(
            model_name='calculatedfieldvaluehistory',
            index=models.Index(fields=['batch_id'], name='governance__batch_i_9b0a53_idx'),
        ),
        migrations.AddIndex(
            model_name='calculatedfieldvaluehistory',
            index=models.Index(fields=['professional_scope', 'calculation_field_code', '-created_at'], name='governance__profess_8158e4_idx'),
        ),
    ]
