# Generated by Django 5.2.11 on 2026-09-11 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('competency', '0004_alter_competencyassessment_assessment_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('evidence', '0002_initial'),
        ('governance', '0004_alter_calculatedfieldoverride_options_and_more'),
        ('professionals', '0004_add_calculated_experience_fields'),
        ('tenancy', '0003_alter_project_business_unit_alter_project_industry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculatedfieldoverride',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveConstraint(
            model_name='calculatedfieldoverride',
            name='chk_calc_override_decision_reason_required_on_rejection',
        ),
        migrations.RemoveConstraint(
            model_name='calculatedfieldoverride',
            name='chk_calc_override_approved_at_required',
        ),
        migrations.RemoveConstraint(
            model_name='calculatedfieldoverride',
            name='chk_calc_override_evidence_required_for_exception',
        ),
        migrations.RemoveConstraint(
            model_name='calculatedfieldvaluehistory',
            name='chk_calc_value_history_override_required',
        ),
        migrations.RemoveIndex(
            model_name='calculatedfieldoverride',
            name='governance__content_0789c8_idx',
        ),
        migrations.RemoveField(
            model_name='calculatedfieldoverride',
            name='supersedes',
        ),
        migrations.AddField(
            model_name='calculatedfieldoverride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='calculatedfieldvaluehistory',
            name='reason',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='calculatedfieldvaluehistory',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('SOURCE_DATA_INCORRECT', 'Source data incorrect'), ('SOURCE_DATA_INCOMPLETE', 'Source data incomplete'), ('RULE_DOES_NOT_FIT_SITUATION', 'Automated rule does not represent the professional situation'), ('EVIDENCE_RECEIVED_LATE', 'Additional evidence received after calculation'), ('SYSTEM_DEFECT', 'System/calculation defect'), ('OTHER', 'Other')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Most recent admin submission batch that updated this override.', null=True),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='field_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='professional_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_field_overrides', to='competency.professionalscope'),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='system_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedfieldoverride',
            name='system_calculated_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedfieldvaluehistory',
            name='field_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='calculatedfieldoverride',
            index=models.Index(fields=['content_type', 'object_id'], name='governance__content_45651b_idx'),
        ),
        migrations.AddConstraint(
            model_name='calculatedfieldoverride',
            constraint=models.UniqueConstraint(fields=('professional', 'calculation_field_code', 'content_type', 'object_id'), name='uq_current_calculated_field_override'),
        ),
    ]
