# Generated by Django 5.2.11 on 2026-09-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0004_tenantregistrationinvite_invitation_type_and_more'),
        ('governance', '0005_alter_calculatedfieldoverride_options_and_more'),
        ('tenancy', '0003_alter_project_business_unit_alter_project_industry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationrule',
            options={'ordering': ['calculation_field_code', 'id'], 'verbose_name': 'Calculation Rule', 'verbose_name_plural': 'Calculation Rules'},
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='concluded_classification',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='concluded_deployability_status',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='concluded_qualion_level',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='max_calendar_experience_months',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='max_qualion_level',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='max_verified_field_days',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='max_verified_project_count',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='min_calendar_experience_months',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='min_complexity_rating',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='min_verified_field_days',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='min_verified_project_count',
        ),
        migrations.RemoveField(
            model_name='calculationrule',
            name='sequence',
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='block_if_pending_rejection',
            field=models.BooleanField(default=False, help_text='If enabled, Mentor classification fails while an unresolved reclassification rejection exists.'),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='calculation_field_code',
            field=models.CharField(blank=True, choices=[('QUALION_LEVEL', 'Qualion Level'), ('DEPLOYABILITY_FLAG', 'Deployability Flag'), ('CANDIDATE_MENTOR_CLASSIFICATION', 'Candidate / Mentor Classification')], db_index=True, help_text='Rule-driven calculated field controlled by this configuration.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rules_created', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Inactive configurations are ignored during calculation.'),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='label',
            field=models.CharField(blank=True, help_text='Admin-facing name for this rule configuration.', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='match_type',
            field=models.CharField(choices=[('ALL_CONDITIONS', 'All conditions must be met'), ('ANY_CONDITION', 'Any one condition is sufficient')], default='ALL_CONDITIONS', help_text='ALL_CONDITIONS means every populated condition must pass. ANY_CONDITION means at least one populated condition must pass.', max_length=20),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='max_days_to_credential_expiry',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional credential expiry condition used by deployability.', null=True),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='min_authority_status',
            field=models.ForeignKey(blank=True, help_text='Minimum authority status required. Used by Deployability and Candidate/Mentor Classification.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rules_min_authority_status', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='min_ethics_independence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum ethics/independence score required to become Mentor.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='min_qualion_level',
            field=models.ForeignKey(blank=True, help_text='Minimum Qualion level required. Used by Deployability and Candidate/Mentor Classification.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rules_min_qualion_level', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='require_active_credential',
            field=models.BooleanField(blank=True, default=False, help_text='If enabled, at least one matching required credential must be active.', null=True),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='require_latest_assessment_decision',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='', help_text='Required latest assessment decision for Mentor classification. Blank means assessment decision is not checked.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='required_credential_types',
            field=models.ManyToManyField(blank=True, help_text='Credential types required for deployability. Empty means credential type is not checked.', null=True, related_name='calculation_rules_required_credentials', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='requires_four_eyes_approval',
            field=models.BooleanField(default=False, help_text='Whether the calculated result requires four-eyes approval.'),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='scope',
            field=models.ManyToManyField(blank=True, help_text='Scopes to which this rule applies. The same configuration may be applied to multiple scopes.', null=True, related_name='calculation_rules', to='catalog.scopecatalog'),
        ),
        migrations.CreateModel(
            name='QualionLevelCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_calendar_experience_months', models.PositiveIntegerField(blank=True, help_text='Minimum calendar experience required in this scope.', null=True)),
                ('min_verified_field_days', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum verified field days required.', max_digits=8, null=True)),
                ('min_verified_project_count', models.PositiveIntegerField(blank=True, help_text='Minimum verified project count required.', null=True)),
                ('require_active_credential', models.BooleanField(default=False, help_text='If enabled, the matching credential must currently be active.')),
                ('is_active', models.BooleanField(default=True, help_text='Disable this particular Qualion level condition.')),
                ('calculation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualion_level_conditions', to='governance.calculationrule')),
                ('min_authority_status', models.ForeignKey(blank=True, help_text='Minimum authority status required for this Qualion level.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualion_conditions_min_authority', to='catalog.referencevalue')),
                ('min_complexity_rating', models.ForeignKey(blank=True, help_text='Minimum complexity rating required for this Qualion level.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualion_conditions_min_complexity', to='catalog.referencevalue')),
                ('qualion_level', models.ForeignKey(help_text='Qualion level represented by this condition combination. Expected values are L5 through L0.', on_delete=django.db.models.deletion.PROTECT, related_name='qualion_level_conditions', to='catalog.referencevalue')),
                ('required_credential_types', models.ManyToManyField(blank=True, help_text='At least one of these credential types must be held. Empty means credentials are not checked for this level.', related_name='qualion_level_conditions_required_credentials', to='catalog.referencevalue')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Qualion Level Condition',
                'verbose_name_plural': 'Qualion Level Conditions',
                'db_table': 'governance_qualion_level_condition',
                'constraints': [models.UniqueConstraint(fields=('calculation_rule', 'qualion_level'), name='uq_calc_rule_qualion_level')],
            },
        ),
    ]
