# Generated by Django 5.2.11 on 2026-10-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_tenantregistrationinvite_invitation_type_and_more'),
        ('governance', '0006_alter_calculationrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrule',
            name='industry',
            field=models.ManyToManyField(blank=True, help_text='Industries to which this rule applies. When industries are selected, the rule automatically applies to every scope belonging to those industries. Industry and Scope cannot both be selected.', limit_choices_to={'option_set__option_type': 'INDUSTRY'}, null=True, related_name='industry_calculation_rules', to='catalog.referencevalue'),
        ),
    ]
