# Generated by Django 5.2.11 on 2026-08-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_code', models.CharField(help_text='Stable code, e.g. SM-WELD; unique with version.', max_length=40)),
                ('module_name', models.CharField(help_text='Module display name.', max_length=180)),
                ('version', models.PositiveIntegerField(default=1, help_text='Module version; unique with module_code.')),
                ('description', models.TextField(blank=True, help_text='Purpose and scope of the module.', max_length=3000)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', help_text='Publication status.', max_length=20)),
                ('effective_from', models.DateField(blank=True, help_text='Effective date; cannot be after retired date.', null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication timestamp; required when PUBLISHED.', null=True)),
                ('retired_at', models.DateTimeField(blank=True, help_text='Retirement timestamp; required when retired.', null=True)),
                ('created_by', models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='form_modules_created', to='accounts.usertbl')),
            ],
            options={
                'verbose_name': 'Form Module',
                'verbose_name_plural': 'Form Modules',
                'db_table': 'catalog_form_module',
                'ordering': ['module_code', 'version'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_code', models.CharField(help_text='Stable machine path; unique within form_module.', max_length=140)),
                ('field_label', models.CharField(help_text='Question label.', max_length=220)),
                ('purpose', models.CharField(blank=True, help_text='Short explanation of why the field is collected.', max_length=300)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('ENUM', 'Enum'), ('ENUM_LIST', 'Enum list'), ('STRING_LIST', 'String list'), ('RICH_TEXT', 'Rich text'), ('FILE', 'File')], help_text='Expected answer type.', max_length=30)),
                ('ui_control', models.CharField(help_text='Frontend input control from the allowed control list (text, textarea, select, multiselect, date, checkbox, number, file, etc).', max_length=50)),
                ('is_required', models.BooleanField(default=False, help_text='Enforced at module/project-scope submission.')),
                ('is_repeatable', models.BooleanField(default=False, help_text='Whether multiple answer groups are allowed; repeatable fields use repeat group/index in ScopeResponse.')),
                ('option_set', models.CharField(blank=True, help_text='Controlled option set name; required for master-driven enum values, must match ReferenceValue.option_set.', max_length=80)),
                ('options_schema', models.JSONField(blank=True, default=dict, help_text='Inline/dependent option configuration; required for inline enum/list values.')),
                ('validation_schema', models.JSONField(blank=True, default=dict, help_text='Answer validation rules; must be compatible with data_type.')),
                ('evidence_rule', models.JSONField(blank=True, default=dict, help_text='Expected supporting evidence.')),
                ('resume_token', models.CharField(blank=True, help_text='Token available to resume mapping; unique where populated.', max_length=180)),
                ('default_resume_visibility', models.CharField(choices=[('NEVER', 'Never'), ('ALWAYS', 'Always'), ('OPTIONAL', 'Optional'), ('CLIENT_SPECIFIC', 'Client specific')], default='OPTIONAL', help_text='Default resume display rule.', max_length=30)),
                ('data_classification', models.CharField(choices=[('PUBLIC', 'Public'), ('PROFESSIONAL', 'Professional'), ('SENSITIVE_PII', 'Sensitive PII'), ('RESTRICTED_PII', 'Restricted PII'), ('COMMERCIAL', 'Commercial'), ('HEALTH', 'Health')], default='PROFESSIONAL', help_text='Data sensitivity level.', max_length=30)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Field display order; unique sequence recommended within module.')),
                ('is_active', models.BooleanField(default=True, help_text='Selection/display status; inactive fields remain readable for historical responses.')),
                ('created_by', models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='form_fields_created', to='accounts.usertbl')),
                ('form_module', models.ForeignKey(help_text='Owning form module; field belongs to one module version.', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalog.formmodule')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'db_table': 'catalog_form_field',
                'ordering': ['form_module', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_set', models.CharField(db_index=True, help_text='Category of controlled value, e.g. INDUSTRY, QUALION_LEVEL, AUTHORITY_STATUS, CAREER_STAGE, QUALIFICATION_LEVEL, PROFESSIONAL_ROLE, STANDARD, EQUIPMENT, SOFTWARE.', max_length=80)),
                ('code', models.CharField(help_text='Stable uppercase machine code; unique with option_set.', max_length=80)),
                ('label', models.CharField(help_text='User-facing display value.', max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display order.')),
                ('is_system', models.BooleanField(default=True, help_text='Marks protected platform baseline value.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive values remain for historical references.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional master configuration; schema depends on option_set.')),
                ('created_by', models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='reference_values_created', to='accounts.usertbl')),
                ('parent', models.ForeignKey(blank=True, help_text='Supports dependent values. Parent must be from the same or compatible option set; no cycles.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.referencevalue')),
            ],
            options={
                'verbose_name': 'Reference Value',
                'verbose_name_plural': 'Reference Values',
                'db_table': 'catalog_reference_value',
                'ordering': ['option_set', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ScopeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Globally unique stable code, e.g. OG-LPM.', max_length=40, unique=True)),
                ('scope_name', models.CharField(help_text='Survey or inspection scope name; unique with industry among active scopes.', max_length=180)),
                ('description', models.TextField(blank=True, help_text='Scope description.', max_length=3000)),
                ('competency_focus', models.TextField(blank=True, help_text='Competency direction for the scope.', max_length=3000)),
                ('suggested_resume_section', models.CharField(blank=True, help_text='Recommended resume section title (template hint only).', max_length=160)),
                ('activation_rule', models.JSONField(blank=True, default=dict, help_text='Optional rules controlling scope/module activation.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Scope definition version; increment for material published changes.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', help_text='Publication status.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Selection availability; retired scopes remain readable.')),
                ('created_by', models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='scope_catalogs_created', to='accounts.usertbl')),
                ('industry', models.ForeignKey(help_text='Industry to which the scope belongs. option_set must be INDUSTRY.', on_delete=django.db.models.deletion.PROTECT, related_name='scopes', to='catalog.referencevalue')),
            ],
            options={
                'verbose_name': 'Scope Catalog',
                'verbose_name_plural': 'Scope Catalogs',
                'db_table': 'catalog_scope_catalog',
                'ordering': ['industry', 'scope_name'],
            },
        ),
        migrations.CreateModel(
            name='ScopeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0, help_text='Module display order; unique rendering sequence within scope.')),
                ('is_required', models.BooleanField(default=True, help_text='Required modules cannot be skipped at scope submission.')),
                ('activation_rule', models.JSONField(blank=True, default=dict, help_text='Optional conditional loading rule.')),
                ('effective_from', models.DateField(blank=True, help_text='Mapping start date; cannot be after effective_to.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Mapping end date; must be on/after effective_from.', null=True)),
                ('created_by', models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='scope_modules_created', to='accounts.usertbl')),
                ('form_module', models.ForeignKey(help_text='Reusable module assigned to the scope; published scope may use only a published module version.', on_delete=django.db.models.deletion.PROTECT, related_name='scope_modules', to='catalog.formmodule')),
                ('scope', models.ForeignKey(help_text='Scope being configured; must be active or draft during configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='scope_modules', to='catalog.scopecatalog')),
            ],
            options={
                'verbose_name': 'Scope Module',
                'verbose_name_plural': 'Scope Modules',
                'db_table': 'catalog_scope_module',
                'ordering': ['scope', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='formmodule',
            constraint=models.UniqueConstraint(fields=('module_code', 'version'), name='uniq_form_module_code_version'),
        ),
        migrations.AddConstraint(
            model_name='formmodule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PUBLISHED'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='chk_form_module_published_at_required'),
        ),
        migrations.AddConstraint(
            model_name='formmodule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'RETIRED'), _negated=True), ('retired_at__isnull', False), _connector='OR'), name='chk_form_module_retired_at_required'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('form_module', 'field_code'), name='uniq_form_field_module_code'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(condition=models.Q(('resume_token', ''), _negated=True), fields=('resume_token',), name='uniq_form_field_resume_token'),
        ),
        migrations.AddConstraint(
            model_name='referencevalue',
            constraint=models.UniqueConstraint(fields=('option_set', 'code'), name='uniq_reference_value_option_set_code'),
        ),
        migrations.AddConstraint(
            model_name='scopecatalog',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('industry', 'scope_name'), name='uniq_scope_catalog_industry_scope_name_active'),
        ),
        migrations.AddConstraint(
            model_name='scopemodule',
            constraint=models.UniqueConstraint(fields=('scope', 'sequence'), name='uniq_scope_module_scope_sequence'),
        ),
        migrations.AddConstraint(
            model_name='scopemodule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_from__isnull', True), ('effective_to__isnull', True), ('effective_from__lte', models.F('effective_to')), _connector='OR'), name='chk_scope_module_effective_from_before_to'),
        ),
    ]
