"""Hand-written migration — not generated by makemigrations.

catalog/migrations/0001_initial.py was regenerated in place at some point
to describe ReferenceValue.option_set as a ForeignKey to
ReferencevalueoptionSet, but that never ran against every database that
had already applied the migration under its old content (option_set as a
plain CharField, no ReferencevalueoptionSet table at all). Because Django
only records migrations as applied/unapplied by name, `migrate` sees
'catalog.0001_initial' as already applied and does nothing, and
`makemigrations` diffs models against the *current* migration file content
(which already matches the models) and reports no changes either — so
neither command can detect or fix this on its own.

This migration inspects the live schema directly and, only if it finds the
old shape, backfills it into the new one: creates
catalog_referencevalueoptionset, populates it from the distinct existing
option_set string values, adds option_set_id, backfills it, and drops the
old string column. It's a no-op on any database that's already correct
(fresh installs that only ever saw the current 0001_initial content).
"""

from django.db import migrations


def fix_option_set_drift(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(catalog_reference_value)")
        columns = {row[1] for row in cursor.fetchall()}
        if "option_set_id" in columns:
            return

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS catalog_referencevalueoptionset (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                option_type varchar(80) NULL
            )
            """
        )

        cursor.execute(
            "SELECT DISTINCT option_set FROM catalog_reference_value "
            "WHERE option_set IS NOT NULL AND option_set != ''"
        )
        distinct_values = [row[0] for row in cursor.fetchall()]

        value_to_id = {}
        for value in distinct_values:
            cursor.execute(
                "SELECT id FROM catalog_referencevalueoptionset WHERE option_type = %s",
                [value],
            )
            existing = cursor.fetchone()
            if existing:
                value_to_id[value] = existing[0]
                continue
            cursor.execute(
                "INSERT INTO catalog_referencevalueoptionset (option_type) VALUES (%s)",
                [value],
            )
            cursor.execute("SELECT last_insert_rowid()")
            value_to_id[value] = cursor.fetchone()[0]

        cursor.execute(
            "ALTER TABLE catalog_reference_value ADD COLUMN option_set_id bigint NULL "
            "REFERENCES catalog_referencevalueoptionset(id)"
        )

        for value, option_set_id in value_to_id.items():
            cursor.execute(
                "UPDATE catalog_reference_value SET option_set_id = %s WHERE option_set = %s",
                [option_set_id, value],
            )

        # A plain DROP COLUMN isn't enough here: the old column is still
        # bound by the original uniq_reference_value_option_set_code table
        # constraint (UNIQUE(option_set, code)), and SQLite refuses to drop
        # a column referenced by a UNIQUE/PRIMARY KEY constraint. Rebuild
        # the table instead — the standard SQLite pattern for this — using
        # the correct final constraint (UNIQUE(option_set_id, code), which
        # is what the current model's UniqueConstraint(["option_set",
        # "code"]) actually compiles to, since "option_set" is now the FK
        # field name mapping to the option_set_id column).
        cursor.execute(
            """
            CREATE TABLE catalog_reference_value_new (
              id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
              created_at datetime NOT NULL,
              updated_at datetime NOT NULL,
              code varchar(80) NOT NULL,
              label varchar(160) NOT NULL,
              sort_order smallint unsigned NOT NULL CHECK (sort_order >= 0),
              is_system bool NOT NULL,
              is_active bool NOT NULL,
              metadata text NOT NULL CHECK ((JSON_VALID(metadata) OR metadata IS NULL)),
              created_by_id bigint NOT NULL REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED,
              parent_id bigint NULL REFERENCES catalog_reference_value_new (id) DEFERRABLE INITIALLY DEFERRED,
              option_set_id bigint NULL REFERENCES catalog_referencevalueoptionset (id) DEFERRABLE INITIALLY DEFERRED,
              CONSTRAINT uniq_reference_value_option_set_code UNIQUE (option_set_id, code),
              CONSTRAINT chk_reference_value_parent_not_self CHECK (NOT (parent_id = id AND parent_id IS NOT NULL))
            )
            """
        )
        cursor.execute(
            """
            INSERT INTO catalog_reference_value_new
              (id, created_at, updated_at, code, label, sort_order, is_system, is_active, metadata, created_by_id, parent_id, option_set_id)
            SELECT
              id, created_at, updated_at, code, label, sort_order, is_system, is_active, metadata, created_by_id, parent_id, option_set_id
            FROM catalog_reference_value
            """
        )
        cursor.execute("DROP TABLE catalog_reference_value")
        cursor.execute("ALTER TABLE catalog_reference_value_new RENAME TO catalog_reference_value")
        cursor.execute("CREATE INDEX catalog_reference_value_created_at_idx ON catalog_reference_value (created_at)")
        cursor.execute("CREATE INDEX catalog_reference_value_created_by_id_idx ON catalog_reference_value (created_by_id)")
        cursor.execute("CREATE INDEX catalog_reference_value_parent_id_idx ON catalog_reference_value (parent_id)")
        cursor.execute("CREATE INDEX catalog_reference_value_option_set_id_idx ON catalog_reference_value (option_set_id)")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fix_option_set_drift, noop_reverse),
    ]
