# Generated by Django 5.2.11 on 2026-07-31 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='created_by',
            field=models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='form_fields_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formmodule',
            name='created_by',
            field=models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='form_modules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referencevalue',
            name='created_by',
            field=models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='reference_values_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scopecatalog',
            name='created_by',
            field=models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='scope_catalogs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scopemodule',
            name='created_by',
            field=models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='scope_modules_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
