# Generated by Django 5.2.11 on 2026-09-03 06:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0002_fix_schema_drift'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRegistrationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('registered_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('invitation_date_time', models.DateTimeField(auto_now_add=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('registered_date_time', models.DateTimeField(blank=True, null=True)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_registration_invites', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tenant_registration_invite',
                'ordering': ['-invitation_date_time'],
            },
        ),
    ]
