# Generated by Django 5.2.11 on 2026-08-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['form_module', 'sequence'], 'verbose_name': 'FormField', 'verbose_name_plural': 'FormField'},
        ),
        migrations.AlterModelOptions(
            name='formmodule',
            options={'ordering': ['module_code', 'version'], 'verbose_name': 'FormModule', 'verbose_name_plural': 'FormModule'},
        ),
        migrations.AlterModelOptions(
            name='referencevalue',
            options={'ordering': ['option_set', 'sort_order', 'label'], 'verbose_name': 'ReferenceValue', 'verbose_name_plural': 'ReferenceValue'},
        ),
        migrations.AlterModelOptions(
            name='scopecatalog',
            options={'ordering': ['industry', 'scope_name'], 'verbose_name': 'ScopeCatalog', 'verbose_name_plural': 'ScopeCatalog'},
        ),
        migrations.AlterModelOptions(
            name='scopemodule',
            options={'ordering': ['scope', 'sequence'], 'verbose_name': 'ScopeModule', 'verbose_name_plural': 'ScopeModule'},
        ),
    ]
