# Generated by Django 5.2.11 on 2026-09-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tenantregistrationinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('DURATION', 'Duration'), ('RECORD', 'Record'), ('ENUM', 'Enum'), ('ENUM_LIST', 'Enum list'), ('ENUM_SCORE', 'Enum / score'), ('ENUM_DETAILS', 'Enum + details'), ('STRING_LIST', 'String list'), ('LOCATION_LIST', 'Location list'), ('NUMBER_RANGE', 'Number range'), ('NUMBER_UNIT', 'Number + unit'), ('NUMBER_UNITS', 'Number + units'), ('NUMBER_TEXT', 'Number + text'), ('NUMBER_PAIR_UNITS', 'Number pair + units'), ('INTEGER_TEXT', 'Integer + text'), ('INTEGER_PAIR', 'Integer pair'), ('DECIMAL_UNIT', 'Decimal + unit'), ('STRING_NUMBER', 'String + number'), ('BOOLEAN_DETAILS', 'Boolean + details'), ('BOOLEAN_NUMBER', 'Boolean + number'), ('ACTIVITY_LEVEL', 'Activity level'), ('ACTIVITY_RECORD', 'Activity record'), ('CREDENTIAL_LINK', 'Credential link'), ('CREDENTIAL_LINKS', 'Credential links'), ('REPEATABLE_CREDENTIAL_LINK', 'Repeatable credential link'), ('RICH_TEXT', 'Rich text'), ('FILE', 'File')], help_text='Expected answer type.', max_length=30),
        ),
    ]
