# Generated by Django 5.2.11 on 2026-08-01 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otpverification'),
        ('catalog', '0002_alter_formfield_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='created_by',
            field=models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='form_fields_created', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='formmodule',
            name='created_by',
            field=models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='form_modules_created', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='referencevalue',
            name='created_by',
            field=models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='reference_values_created', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='scopecatalog',
            name='created_by',
            field=models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='scope_catalogs_created', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='scopemodule',
            name='created_by',
            field=models.ForeignKey(help_text='Creator; Platform Super Admin only.', on_delete=django.db.models.deletion.PROTECT, related_name='scope_modules_created', to='accounts.usertbl'),
        ),
    ]
