# Generated by Django 5.2.11 on 2026-09-23 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0003_alter_formfield_data_type'),
        ('tenancy', '0003_alter_project_business_unit_alter_project_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantregistrationinvite',
            name='invitation_type',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('USER', 'User')], db_index=True, default='TENANT', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantregistrationinvite',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role assigned to invited user. Required only for USER invitations.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_invites', to='accounts.roles'),
        ),
        migrations.AddField(
            model_name='tenantregistrationinvite',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Required for USER invitations. NULL for new TENANT invitations.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_invites', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='tenantregistrationinvite',
            name='user_rec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_registration_invites', to='accounts.usertbl'),
        ),
        migrations.AlterField(
            model_name='tenantregistrationinvite',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tenantregistrationinvite',
            name='is_registered',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tenantregistrationinvite',
            name='tenant_rec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_registration_invites', to='tenancy.tenant'),
        ),
    ]
