# Generated by Django 5.2.11 on 2026-08-03 10:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_date', models.DateField(help_text='Date of field/site activity; normally within project dates.')),
                ('hours', models.DecimalField(blank=True, decimal_places=2, help_text='Hours worked/exposed; greater than 0 and <=24.', max_digits=5, null=True)),
                ('day_fraction', models.DecimalField(decimal_places=2, default=1, help_text='Fraction of one verified day; greater than 0 and <=1.', max_digits=3)),
                ('site_or_asset', models.CharField(blank=True, help_text='Plant, yard, vessel, site or asset.', max_length=200)),
                ('activity_summary', models.TextField(help_text='Summary of activity and learning/execution.', max_length=2000)),
                ('verification_status', models.CharField(choices=[('SELF_DECLARED', 'Self declared'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('PENDING_REVIEW', 'Pending review'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='SELF_DECLARED', help_text='Evidence/validation state.', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Required for approved/verified status.', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Review comments.', max_length=2000)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', help_text='Log workflow status.', max_length=20)),
            ],
            options={
                'verbose_name': 'Exposure Log',
                'verbose_name_plural': 'Exposure Logs',
                'db_table': 'experience_exposure_log',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('BRANCH', 'Branch'), ('DEPARTMENT', 'Department'), ('OPERATING_UNIT', 'Operating unit'), ('TRAINING_ROTATION', 'Training rotation'), ('PROJECT', 'Project'), ('MENTOR', 'Mentor'), ('TECHNICAL_REVIEW', 'Technical review')], help_text='Type of assignment.', max_length=30)),
                ('start_date', models.DateField(help_text='Assignment start; cannot be after end_date.')),
                ('end_date', models.DateField(blank=True, help_text='Assignment end; must be on/after start_date.', null=True)),
                ('allocation_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Allocation to assignment; greater than 0 and <=100.', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Assignment status.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Assignment notes.', max_length=2000)),
            ],
            options={
                'verbose_name': 'Professional Assignment',
                'verbose_name_plural': 'Professional Assignments',
                'db_table': 'experience_professional_assignment',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Safe external identifier used in APIs and integrations.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(help_text='Project name.', max_length=220)),
                ('client_name_snapshot', models.CharField(help_text='Client name as recorded for project; retained even if organisation renamed.', max_length=200)),
                ('client_alias', models.CharField(blank=True, help_text='Safe client alias, e.g. Confidential International EPC Client. Required when visibility is masked and an alias is used.', max_length=200)),
                ('client_visibility', models.CharField(choices=[('SHOW_CLIENT_NAME', 'Show client name'), ('SHOW_MASKED_CLIENT_CATEGORY', 'Show masked client category'), ('CONFIDENTIAL_DO_NOT_DISPLAY', 'Confidential — do not display')], default='SHOW_CLIENT_NAME', help_text='Client confidentiality rule.', max_length=40)),
                ('country_code', models.CharField(blank=True, help_text='Project country.', max_length=2)),
                ('city', models.CharField(blank=True, help_text='Project city/location.', max_length=120)),
                ('role_title', models.CharField(help_text='Role performed on project.', max_length=160)),
                ('start_date', models.DateField(help_text='Project start date; cannot be after end_date.')),
                ('end_date', models.DateField(blank=True, help_text='Project end date; required unless is_current=true; on/after start_date.', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Current project flag.')),
                ('allocation_percent', models.DecimalField(decimal_places=2, default=100, help_text='Time allocation during the project period; >0 and <=100.', max_digits=5)),
                ('is_primary_assignment', models.BooleanField(default=True, help_text='Primary assignment indicator; normally at most one primary full-time assignment for overlapping period.')),
                ('working_arrangement', models.CharField(blank=True, choices=[('FULL_TIME', 'Full time'), ('ROTATION', 'Rotation'), ('PART_TIME', 'Part time'), ('FREELANCE', 'Freelance')], help_text='Working arrangement.', max_length=50)),
                ('engagement_explanation', models.TextField(blank=True, help_text='Explanation for direct/freelance or chronology exception; required when project dates are outside linked employment/contract.', max_length=1000)),
                ('declared_field_days', models.PositiveIntegerField(blank=True, help_text='Candidate-entered field-day estimate; self-declared only.', null=True)),
                ('verified_field_days', models.DecimalField(decimal_places=2, default=0, help_text='Cached verified field days; derived from approved ExposureLog.', max_digits=8)),
                ('responsibilities', models.TextField(blank=True, help_text='Responsibilities and duties; 100-3000 characters, required at project submission.', max_length=3000, validators=[django.core.validators.MinLengthValidator(100)])),
                ('achievements', models.TextField(blank=True, help_text='Key achievements.', max_length=1500)),
                ('standards_applied', models.JSONField(blank=True, default=list, help_text='Codes and standards applied; list of standard reference IDs/codes and optional edition; no duplicates.')),
                ('verification_status', models.CharField(choices=[('SELF_DECLARED', 'Self declared'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('PENDING_REVIEW', 'Pending review'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='SELF_DECLARED', help_text='Verification state.', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETE', 'Complete'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', help_text='Record completion status.', max_length=20)),
            ],
            options={
                'verbose_name': 'Project Record',
                'verbose_name_plural': 'Project Records',
                'db_table': 'experience_project_record',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_summary', models.CharField(blank=True, help_text='Short description of scope activity.', max_length=600)),
                ('verification_status', models.CharField(choices=[('SELF_DECLARED', 'Self declared'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('PENDING_REVIEW', 'Pending review'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='SELF_DECLARED', help_text='Verification state.', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETE', 'Complete'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', help_text='Completion status.', max_length=20)),
            ],
            options={
                'verbose_name': 'Project Scope',
                'verbose_name_plural': 'Project Scopes',
                'db_table': 'experience_project_scope',
                'ordering': ['project', 'scope'],
            },
        ),
        migrations.CreateModel(
            name='ScopeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repeat_group_key', models.UUIDField(default=uuid.uuid4, help_text='Groups repeated fields into one logical record. Non-repeatable fields use one standard group; repeatable fields may use many.')),
                ('repeat_index', models.PositiveSmallIntegerField(default=0, help_text='Order within repeated group.')),
                ('value', models.JSONField(blank=True, help_text='Actual answer value; must pass FormField.data_type, options and validation_schema.', null=True)),
                ('verification_status', models.CharField(choices=[('SELF_DECLARED', 'Self declared'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('PENDING_REVIEW', 'Pending review'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='SELF_DECLARED', help_text='Answer verification state.', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Required when verification status is verified/validated.', null=True)),
            ],
            options={
                'verbose_name': 'Scope Response',
                'verbose_name_plural': 'Scope Responses',
                'db_table': 'experience_scope_response',
                'ordering': ['project_scope', 'form_field', 'repeat_group_key', 'repeat_index'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_name_snapshot', models.CharField(help_text='Employer name preserved for history/resume; required even if employer_organization exists.', max_length=200)),
                ('job_title', models.CharField(help_text='Employment job title.', max_length=160, validators=[django.core.validators.MinLengthValidator(2)])),
                ('country_code', models.CharField(blank=True, help_text='Employment country.', max_length=2)),
                ('city', models.CharField(blank=True, help_text='Employment city.', max_length=120)),
                ('start_date', models.DateField(help_text='Employment start date; cannot be after end_date.')),
                ('end_date', models.DateField(blank=True, help_text='Employment end date; required unless is_current=true; on/after start_date.', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Current employment flag. If true, end_date must be NULL; if false, end_date required.')),
                ('duties', models.TextField(blank=True, help_text='Main duties.', max_length=3000)),
                ('verification_status', models.CharField(choices=[('SELF_DECLARED', 'Self declared'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('PENDING_REVIEW', 'Pending review'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='SELF_DECLARED', help_text='Verification state.', max_length=30)),
                ('resume_visibility', models.CharField(choices=[('NEVER', 'Never'), ('ALWAYS', 'Always'), ('OPTIONAL', 'Optional'), ('CLIENT_SPECIFIC', 'Client specific')], default='ALWAYS', help_text='Resume inclusion rule.', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', help_text='Record lifecycle status.', max_length=20)),
                ('employer_organization', models.ForeignKey(blank=True, help_text='Structured employer. Same tenant; employer type recommended.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employment_records', to='tenancy.organization')),
                ('employment_type', models.ForeignKey(blank=True, help_text='Permanent, contract, rotation, freelance, etc. option_set must be ENGAGEMENT_TYPE.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employment_records', to='catalog.referencevalue')),
            ],
            options={
                'verbose_name': 'Employment Record',
                'verbose_name_plural': 'Employment Records',
                'db_table': 'experience_employment_record',
                'ordering': ['-start_date'],
            },
        ),
    ]
