# Generated by Django 5.2.11 on 2026-08-07 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0001_initial'),
        ('evidence', '0002_initial'),
        ('experience', '0001_initial'),
        ('professionals', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrecord',
            name='professional',
            field=models.ForeignKey(help_text='Professional who owns the employment record.', on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='exposurelog',
            name='professional',
            field=models.ForeignKey(help_text='Professional whose exposure is logged. Must equal project_scope.project.professional.', on_delete=django.db.models.deletion.CASCADE, related_name='exposure_logs', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='exposurelog',
            name='supervisor_professional',
            field=models.ForeignKey(blank=True, help_text='Supervisor/mentor associated with log. Same tenant; cannot equal professional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exposure_logs_supervised', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='exposurelog',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='exposurelog',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Approver/verifier; authorised mentor/reviewer; cannot be the same user where self-verification is prohibited.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exposure_logs_verified', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='professionalassignment',
            name='assigned_by',
            field=models.ForeignKey(help_text='User who created the assignment. Same-tenant Tenant Admin or authorised reviewer.', on_delete=django.db.models.deletion.PROTECT, related_name='professional_assignments_created', to='accounts.usertbl'),
        ),
        migrations.AddField(
            model_name='professionalassignment',
            name='mentor_professional',
            field=models.ForeignKey(blank=True, help_text='Assigned mentor; required for MENTOR assignment; must be confirmed Mentor; cannot equal professional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentor_assignments', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='professionalassignment',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Assigned organisation unit; required for branch/department/operating-unit assignments and type must match.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_assignments', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='professionalassignment',
            name='professional',
            field=models.ForeignKey(help_text='Professional receiving the assignment.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='professionalassignment',
            name='scope',
            field=models.ForeignKey(blank=True, help_text='Optional scope for technical or mentor assignment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_assignments', to='catalog.scopecatalog'),
        ),
        migrations.AddField(
            model_name='professionalassignment',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='projectrecord',
            name='achievement_evidence',
            field=models.ForeignKey(blank=True, help_text='Primary supporting document. Must belong to same professional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_evidence', to='evidence.evidencedocument'),
        ),
        migrations.AddField(
            model_name='projectrecord',
            name='employment',
            field=models.ForeignKey(blank=True, help_text='Employment/contract under which project was performed. Must belong to same professional; dates normally cover project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_records', to='experience.employmentrecord'),
        ),
        migrations.AddField(
            model_name='projectrecord',
            name='industry_classification',
            field=models.ForeignKey(blank=True, help_text='Related industry; used for classification and reporting.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_records', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='projectrecord',
            name='professional',
            field=models.ForeignKey(help_text='Professional who performed the project.', on_delete=django.db.models.deletion.CASCADE, related_name='project_records', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='projectrecord',
            name='role_title',
            field=models.ForeignKey(blank=True, help_text='Role performed on project; option_set must be ROLE_TITLE.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_records_as_role', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='projectrecord',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='projectrecord',
            name='verification_status_evidence',
            field=models.ForeignKey(blank=True, help_text='Primary supporting document. Must belong to same professional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_status_evidence', to='evidence.evidencedocument'),
        ),
        migrations.AddField(
            model_name='professionalassignment',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Assigned project; required for project/technical-review assignments; same tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_assignments', to='experience.projectrecord'),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='authority_action',
            field=models.ForeignKey(help_text='Observed, assisted, performed, reviewed, approved, etc. option_set must be AUTHORITY_ACTION.', on_delete=django.db.models.deletion.PROTECT, related_name='project_scopes', to='catalog.referencevalue'),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='project',
            field=models.ForeignKey(help_text='Owning project. Must equal project.tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='project_scopes', to='experience.projectrecord'),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='scope',
            field=models.ForeignKey(help_text='Scope performed on project; active scope, registration industry does not limit later verified scopes.', on_delete=django.db.models.deletion.PROTECT, related_name='project_scopes', to='catalog.scopecatalog'),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='exposurelog',
            name='project_scope',
            field=models.ForeignKey(help_text='Project and scope for the activity. Same professional and tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='exposure_logs', to='experience.projectscope'),
        ),
        migrations.AddField(
            model_name='scoperesponse',
            name='form_field',
            field=models.ForeignKey(help_text='Question being answered; must belong to an active module mapped to project_scope.scope.', on_delete=django.db.models.deletion.PROTECT, related_name='scope_responses', to='catalog.formfield'),
        ),
        migrations.AddField(
            model_name='scoperesponse',
            name='project_scope',
            field=models.ForeignKey(help_text='Project-scope answer set. Must equal project_scope.tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='scope_responses', to='experience.projectscope'),
        ),
        migrations.AddField(
            model_name='scoperesponse',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='scoperesponse',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Verifier; authorised same-tenant reviewer; cannot verify own answer where separation is required.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scope_responses_verified', to='accounts.usertbl'),
        ),
        migrations.AddConstraint(
            model_name='employmentrecord',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='chk_employment_record_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='employmentrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_current', True), ('end_date__isnull', True)), models.Q(('is_current', False), ('end_date__isnull', False)), _connector='OR'), name='chk_employment_record_is_current_end_date_consistency'),
        ),
        migrations.AddConstraint(
            model_name='projectrecord',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='chk_project_record_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='projectrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_current', True), ('end_date__isnull', True)), models.Q(('is_current', False), ('end_date__isnull', False)), _connector='OR'), name='chk_project_record_is_current_end_date_consistency'),
        ),
        migrations.AddConstraint(
            model_name='projectrecord',
            constraint=models.CheckConstraint(check=models.Q(('allocation_percent__gt', 0), ('allocation_percent__lte', 100)), name='chk_project_record_allocation_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='professionalassignment',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='chk_professional_assignment_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='professionalassignment',
            constraint=models.CheckConstraint(check=models.Q(('allocation_percent__isnull', True), models.Q(('allocation_percent__gt', 0), ('allocation_percent__lte', 100)), _connector='OR'), name='chk_professional_assignment_allocation_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='professionalassignment',
            constraint=models.CheckConstraint(check=models.Q(('mentor_professional', models.F('professional')), _negated=True), name='chk_professional_assignment_mentor_not_self'),
        ),
        migrations.AddConstraint(
            model_name='professionalassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('assignment_type__in', ['BRANCH', 'DEPARTMENT', 'OPERATING_UNIT']), _negated=True), ('organization__isnull', False), _connector='OR'), name='chk_professional_assignment_organization_required'),
        ),
        migrations.AddConstraint(
            model_name='professionalassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('assignment_type__in', ['PROJECT', 'TECHNICAL_REVIEW']), _negated=True), ('project__isnull', False), _connector='OR'), name='chk_professional_assignment_project_required'),
        ),
        migrations.AddConstraint(
            model_name='professionalassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('assignment_type', 'MENTOR'), _negated=True), ('mentor_professional__isnull', False), _connector='OR'), name='chk_professional_assignment_mentor_required'),
        ),
        migrations.AddConstraint(
            model_name='projectscope',
            constraint=models.UniqueConstraint(fields=('project', 'scope'), name='uniq_project_scope_project_scope'),
        ),
        migrations.AddConstraint(
            model_name='exposurelog',
            constraint=models.CheckConstraint(check=models.Q(('hours__isnull', True), models.Q(('hours__gt', 0), ('hours__lte', 24)), _connector='OR'), name='chk_exposure_log_hours_range'),
        ),
        migrations.AddConstraint(
            model_name='exposurelog',
            constraint=models.CheckConstraint(check=models.Q(('day_fraction__gt', 0), ('day_fraction__lte', 1)), name='chk_exposure_log_day_fraction_range'),
        ),
        migrations.AddConstraint(
            model_name='exposurelog',
            constraint=models.CheckConstraint(check=models.Q(('supervisor_professional', models.F('professional')), _negated=True), name='chk_exposure_log_supervisor_not_self'),
        ),
        migrations.AddConstraint(
            model_name='exposurelog',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('verification_status__in', ['VERIFIED', 'VALIDATED']), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='chk_exposure_log_verified_at_required'),
        ),
        migrations.AddConstraint(
            model_name='scoperesponse',
            constraint=models.UniqueConstraint(fields=('project_scope', 'form_field', 'repeat_group_key', 'repeat_index'), name='uniq_scope_response_project_scope_field_group_index'),
        ),
        migrations.AddConstraint(
            model_name='scoperesponse',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('verification_status__in', ['VERIFIED', 'VALIDATED']), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='chk_scope_response_verified_at_required'),
        ),
    ]
