# Generated by Django 5.2.11 on 2026-08-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('experience', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectscope',
            name='authority_action',
            field=models.ForeignKey(blank=True, help_text='Observed, assisted, performed, reviewed, approved, etc. option_set must be AUTHORITY_ACTION.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_scopes', to='catalog.referencevalue'),
        ),
    ]
