# Generated by Django 5.2.11 on 2026-09-03 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tenantregistrationinvite'),
        ('experience', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrecord',
            name='employment',
            field=models.ForeignKey(blank=True, help_text='Employment/contract under which project was performed. Must belong to same professional; dates normally cover project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_project_records', to='experience.employmentrecord'),
        ),
        migrations.AlterField(
            model_name='projectrecord',
            name='industry_classification',
            field=models.ForeignKey(blank=True, help_text='Related industry; used for classification and reporting.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_records_industry', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='projectscope',
            name='authority_action',
            field=models.ForeignKey(blank=True, help_text='Observed, assisted, performed, reviewed, approved, etc. option_set must be AUTHORITY_ACTION.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_record_authority', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='projectscope',
            name='scope',
            field=models.ForeignKey(help_text='Scope performed on project; active scope, registration industry does not limit later verified scopes.', on_delete=django.db.models.deletion.PROTECT, related_name='project_record_scopes', to='catalog.scopecatalog'),
        ),
    ]
