# Generated by Django 5.2.11 on 2026-08-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_alter_projectscope_authority_action'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scoperesponse',
            name='uniq_scope_response_project_scope_field_group_index',
        ),
    ]
