# Generated by Django 5.2.11 on 2026-09-03 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tenantregistrationinvite'),
        ('experience', '0003_alter_projectrecord_employment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoperesponse',
            name='form_field',
            field=models.ForeignKey(help_text='Question being answered; must belong to an active module mapped to project_scope.scope.', on_delete=django.db.models.deletion.PROTECT, related_name='scope_responses_fields', to='catalog.formfield'),
        ),
    ]
