# Generated by Django 5.2.11 on 2026-09-11 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_alter_scoperesponse_form_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoperesponse',
            name='repeat_group_key',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Groups repeated fields into one logical record. Non-repeatable fields use one standard group; repeatable fields may use many.', null=True),
        ),
    ]
