# Generated by Django 5.2.11 on 2026-08-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_remove_scoperesponse_uniq_scope_response_project_scope_field_group_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmentrecord',
            options={'ordering': ['-start_date'], 'verbose_name': 'EmploymentRecord', 'verbose_name_plural': 'EmploymentRecord'},
        ),
        migrations.AlterModelOptions(
            name='exposurelog',
            options={'ordering': ['-activity_date'], 'verbose_name': 'ExposureLog', 'verbose_name_plural': 'ExposureLog'},
        ),
        migrations.AlterModelOptions(
            name='professionalassignment',
            options={'ordering': ['-start_date'], 'verbose_name': 'ProfessionalAssignment', 'verbose_name_plural': 'ProfessionalAssignment'},
        ),
        migrations.AlterModelOptions(
            name='projectrecord',
            options={'ordering': ['-start_date'], 'verbose_name': 'ProjectRecord', 'verbose_name_plural': 'ProjectRecord'},
        ),
        migrations.AlterModelOptions(
            name='projectscope',
            options={'ordering': ['project', 'scope'], 'verbose_name': 'ProjectScope', 'verbose_name_plural': 'ProjectScope'},
        ),
        migrations.AlterModelOptions(
            name='scoperesponse',
            options={'ordering': ['project_scope', 'form_field', 'repeat_group_key', 'repeat_index'], 'verbose_name': 'ScopeResponse', 'verbose_name_plural': 'ScopeResponse'},
        ),
    ]
