"""Hand-written migration — not generated by makemigrations.

Same root cause as catalog/migrations/0002_fix_option_set_fk_drift.py and
professionals/migrations/0003_fix_schema_drift.py: experience's earlier
migrations were edited in place after already being applied to some
databases.

Affects EmploymentRecord (employer_organization drifted from an old
ForeignKey column, employer_organization_id, to the current plain
CharField, employer_organization; missing evidence) and ProjectRecord
(several fields added/renamed: Experience_classification,
achievement_evidence, industry_classification, verification_status_evidence
missing; client_organization and employer_organization drifted from FK to
CharField same as above; role_title drifted from CharField to ForeignKey;
client_alias removed).

Only rebuilds a table when it's both drifted AND empty — see the
professionals migration this mirrors for why that's the safe boundary.
"""

from django.db import migrations


def _columns(cursor, table):
    cursor.execute(f"PRAGMA table_info({table})")
    return {row[1] for row in cursor.fetchall()}


def _row_count(cursor, table):
    cursor.execute(f"SELECT COUNT(*) FROM {table}")
    return cursor.fetchone()[0]


def fix_drift(apps, schema_editor):
    EmploymentRecord = apps.get_model("experience", "EmploymentRecord")
    ProjectRecord = apps.get_model("experience", "ProjectRecord")

    with schema_editor.connection.cursor() as cursor:
        for model in (EmploymentRecord, ProjectRecord):
            table = model._meta.db_table
            expected = {f.column for f in model._meta.get_fields() if hasattr(f, "column")}
            actual = _columns(cursor, table)
            if not (expected - actual):
                continue
            if _row_count(cursor, table) != 0:
                raise RuntimeError(
                    f"{table} has drifted from the current model shape and "
                    "already has rows — rebuilding it automatically would "
                    "lose data. Reconcile it by hand before migrating."
                )
            cursor.execute(f'DROP TABLE "{table}"')
            schema_editor.create_model(model)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0004_remove_scoperesponse_uniq_scope_response_project_scope_field_group_index"),
    ]

    operations = [
        migrations.RunPython(fix_drift, noop_reverse),
    ]
