# Generated by Django 5.2.11 on 2026-08-26 11:18

import django.db.models.deletion
import evidence.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Safe external identifier used in APIs and integrations.', unique=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('file', models.FileField(blank=True, max_length=1000, null=True, upload_to=evidence.models.evidence_upload_path)),
                ('original_file_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('data_classification', models.CharField(choices=[('PUBLIC', 'Public'), ('PROFESSIONAL', 'Professional'), ('SENSITIVE_PII', 'Sensitive PII'), ('RESTRICTED_PII', 'Restricted PII'), ('COMMERCIAL', 'Commercial'), ('HEALTH', 'Health')], max_length=30)),
                ('resume_visibility', models.CharField(choices=[('NEVER', 'Never'), ('ALWAYS', 'Always'), ('OPTIONAL', 'Optional'), ('CLIENT_SPECIFIC', 'Client specific')], default='NEVER', max_length=30)),
                ('verification_status', models.CharField(choices=[('SELF_DECLARED', 'Self declared'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('PENDING_REVIEW', 'Pending review'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='EVIDENCE_UPLOADED', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SCANNING', 'Scanning'), ('SAFE', 'Safe'), ('PARSING', 'Parsing'), ('PARSED', 'Parsed'), ('FAILED', 'Failed'), ('USER_CONFIRMED', 'User Confirmed')], db_index=True, default='UPLOADED', max_length=30)),
                ('parser_version', models.CharField(blank=True, max_length=40)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('user_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_documents', to='contenttypes.contenttype')),
                ('evidence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_documents', to='catalog.referencevalue')),
            ],
            options={
                'verbose_name': 'EvidenceDocument',
                'verbose_name_plural': 'EvidenceDocument',
                'db_table': 'evidence_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
