# Generated by Django 5.2.11 on 2026-07-31 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Safe external identifier used in APIs and integrations.', unique=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('object_id', models.PositiveBigIntegerField(help_text='Primary key of supported claim; target must exist and belong to same tenant/professional.')),
                ('original_file_name', models.CharField(help_text='Original uploaded file name; sanitised, path characters removed.', max_length=255)),
                ('storage_key', models.CharField(help_text='Tenant-prefixed object-storage path/key.', max_length=600, unique=True)),
                ('mime_type', models.CharField(help_text='File media type; must be in allowed MIME list and match inspected content.', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(help_text='File size in bytes; must be within evidence-type limit.')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 or stronger content integrity hash.', max_length=128)),
                ('issuer', models.CharField(blank=True, help_text='Document issuer.', max_length=200)),
                ('issue_date', models.DateField(blank=True, help_text='Document issue date; cannot be after expiry_date.', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Document expiry date; on/after issue_date.', null=True)),
                ('data_classification', models.CharField(choices=[('PUBLIC', 'Public'), ('PROFESSIONAL', 'Professional'), ('SENSITIVE_PII', 'Sensitive PII'), ('RESTRICTED_PII', 'Restricted PII'), ('COMMERCIAL', 'Commercial'), ('HEALTH', 'Health')], help_text='Privacy classification; cannot be less restrictive than evidence type default.', max_length=30)),
                ('resume_visibility', models.CharField(choices=[('NEVER', 'Never'), ('ALWAYS', 'Always'), ('OPTIONAL', 'Optional'), ('CLIENT_SPECIFIC', 'Client specific')], default='NEVER', help_text='Whether the document itself can be used/shown in resume context.', max_length=30)),
                ('verification_status', models.CharField(choices=[('SELF_DECLARED', 'Self declared'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('PENDING_REVIEW', 'Pending review'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='EVIDENCE_UPLOADED', help_text='Verification state.', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Required for verified status.', null=True)),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SCANNING', 'Scanning'), ('SAFE', 'Safe'), ('PARSING', 'Parsing'), ('PARSED', 'Parsed'), ('FAILED', 'Failed'), ('USER_CONFIRMED', 'User confirmed')], db_index=True, default='UPLOADED', help_text='File-processing state.', max_length=30)),
                ('parser_version', models.CharField(blank=True, help_text='Resume/document parser version; required when extracted_data is generated.', max_length=40)),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Data extracted from uploaded resume/document; proposed values only, never includes password/OTP.')),
                ('user_confirmed_at', models.DateTimeField(blank=True, help_text='Set after user confirms imported values.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional file metadata; no secrets.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Upload timestamp.')),
                ('content_type', models.ForeignKey(help_text='Model type of the supported claim (restricted allow-list of supported models).', on_delete=django.db.models.deletion.PROTECT, related_name='evidence_documents', to='contenttypes.contenttype')),
                ('evidence_type', models.ForeignKey(help_text='Certificate, timesheet, report, government ID, photograph, resume, etc. option_set must be EVIDENCE_TYPE.', on_delete=django.db.models.deletion.PROTECT, related_name='evidence_documents', to='catalog.referencevalue')),
            ],
            options={
                'verbose_name': 'Evidence Document',
                'verbose_name_plural': 'Evidence Documents',
                'db_table': 'evidence_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
