# Generated by Django 5.2.11 on 2026-08-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('evidence', '0001_initial'),
        ('professionals', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencedocument',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_documents', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this record. Server-derived; never trusted from client payload.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_documents_verified', to='accounts.usertbl'),
        ),
        migrations.AddConstraint(
            model_name='evidencedocument',
            constraint=models.CheckConstraint(condition=models.Q(('issue_date__isnull', True), ('expiry_date__isnull', True), ('issue_date__lte', models.F('expiry_date')), _connector='OR'), name='chk_evidence_document_issue_before_expiry'),
        ),
        migrations.AddConstraint(
            model_name='evidencedocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification_status__in', ['VERIFIED', 'VALIDATED']), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='chk_evidence_document_verified_at_required'),
        ),
    ]
