# Generated by Django 5.2.11 on 2026-08-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidencedocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'EvidenceDocument', 'verbose_name_plural': 'EvidenceDocument'},
        ),
    ]
