# Generated by Django 5.2.11 on 2026-07-31 10:07

import django.db.models.deletion
import evidence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_roles_code'),
        ('catalog', '0002_alter_formfield_created_by_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('evidence', '0002_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencedocument',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='evidencedocument',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='evidencedocument',
            name='storage_key',
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=evidence.models.evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_documents', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='data_classification',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PROFESSIONAL', 'Professional'), ('SENSITIVE_PII', 'Sensitive PII'), ('RESTRICTED_PII', 'Restricted PII'), ('COMMERCIAL', 'Commercial'), ('HEALTH', 'Health')], max_length=30),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='evidence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_documents', to='catalog.referencevalue'),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='issuer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='parser_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SCANNING', 'Scanning'), ('SAFE', 'Safe'), ('PARSING', 'Parsing'), ('PARSED', 'Parsed'), ('FAILED', 'Failed'), ('USER_CONFIRMED', 'User Confirmed')], db_index=True, default='UPLOADED', max_length=30),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_documents', to='professionals.professionalprofile'),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='resume_visibility',
            field=models.CharField(choices=[('NEVER', 'Never'), ('ALWAYS', 'Always'), ('OPTIONAL', 'Optional'), ('CLIENT_SPECIFIC', 'Client specific')], default='NEVER', max_length=30),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='user_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='verification_status',
            field=models.CharField(choices=[('SELF_DECLARED', 'Self declared'), ('EVIDENCE_UPLOADED', 'Evidence uploaded'), ('PENDING_REVIEW', 'Pending review'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='EVIDENCE_UPLOADED', max_length=30),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_documents_verified', to='accounts.usertbl'),
        ),
    ]
